### ISSUE TITLE
Driver version 418.67 require --privileged for authority to execute nvprof

### ISSUE THREAD

**Issue by PeterHuang2015** [NVIDIA/nvidia-docker#1041]
Met the same problem as described in https://codeyarns.github.io/tech/2019-05-08-nvprof-in-nvidia-docker-permissions-warning.html, the given solution is add `--privileged` when running container but it could be unsafe, any idea of the causation which made us unable to nvprof without host machine root pls?

**Comment by liucimin** [comment]
https://github.com/NVIDIA/nvidia-docker/issues/997

**Comment by RenaudWasTaken** [comment]
In all likelihood this is because profiling requires higher privileges.

So for example if you run a normal container, you won't be able to strace programs, you'll need to add the `CAP_SYSTRACE` to your container. I would expect that for profiling you need `CAP_SYS_ADMIN`. `--privileged` gives you all the caps :)
