### ISSUE TITLE
Cudnn Header files in L4T Docker

### ISSUE THREAD

**Issue by ohlr** [NVIDIA/nvidia-docker#1072]
Is there a way to get cudnn header files inside the l4t image?

This question was posted already but there is no official answer.

> is there a way to include the headers in the image? The headers are also needed when building from source, as is the case with PyTorch and other libraries.

_Originally posted by @ilanbiala in https://github.com/NVIDIA/nvidia-docker/issues/1032#issuecomment-521245832_

**Comment by RenaudWasTaken** [comment]
Hello!

Thanks for the input, we'll likely publish a CUDA container in a future release.
Keeping this open for now

**Comment by ohlr** [comment]
Hi @RenaudWasTaken is there a timeline when to expect such release? Weeks, months, years?

**Comment by trn84** [comment]
If you add the official nvidia jetson and common deb sources to your apt you can install libcudnn7 etc in your l4t docker image. I have used this install TensorRT, libnvinfer etc...

**Comment by didibaba** [comment]
@trn84 Could you please give more information about the official nvidia jetson and common deb sources and detailed instructions for installation. THX!

**Comment by trn84** [comment]
> @trn84 Could you please give more information about the official nvidia jetson and common deb sources and detailed instructions for installation. THX!

Hi didibaba,

the .deb file sources are part of the JetPack SDK. If you download the Linux_for_Tegra folder there is a subfolder in the rootfs where you can find the sources.list under /etc/apt/...Btw you can also directly copy the .deb packages locally from the L4T folders...

However, another way that could be interesting is to you a "build" image and a "runtime" image. Since the storage resources of the jetson are rather limited I would suggest such an approach. You can take a look at the guide that I wrote: 

https://medium.com/@trn84/creating-a-cross-compilation-like-process-for-jetson-tx2-aarch64-using-qemu-with-docker-5cb38f6a65bc

You can copy your artifacts from this "build" image into a "runtime" image which would be the official l4t nvidia image that mounts all cuda libs during runtime from the host.

BR

**Comment by didibaba** [comment]
@trn84 Thank you for your quick answer! I'll try this.

**Comment by didibaba** [comment]
@trn84 
After I added the nvidia repository, I got the error "The repository 'https://repo.download.nvidia.com/jetson/<SOC> r32.4 Release' does not have a Release file." when executing `apt update`. Have you met this before?

**Comment by elezar** [comment]
The containers for l4t have changed significantly since this was originally opened.

If problems exist with an up to date version of the NVIDIA Container Toolkit, please open an issue against https://github.com/NVIDIA/nvidia-container-toolkit
