### ISSUE TITLE
Could not connect to nvidia.github.io:443 (185.199.108.153)

### ISSUE THREAD

**Issue by RichardMLe** [NVIDIA/nvidia-docker#1086]
Today, when I wan't to install docker & nvidia-docker behind **proxy**, it got this problom:
'Could not connect to nvidia.github.io:443 (185.199.110.153)'
**I could install docker behind proxy, but could not install nvidia-docker.**
`$: sudo apt update`
`Get:1 file:/var/cuda-repo-10-1-local-10.1.105-418.39  InRelease`
`Ign:1 file:/var/cuda-repo-10-1-local-10.1.105-418.39  InRelease`
`Get:2 file:/var/cuda-repo-10-1-local-10.1.105-418.39  Release [574 B]`
`Get:2 file:/var/cuda-repo-10-1-local-10.1.105-418.39  Release [574 B]`
`Hit:4 https://download.docker.com/linux/ubuntu bionic InRelease`
`Err:5 https://nvidia.github.io/libnvidia-container/ubuntu18.04/amd64  InRelease`
`Could not connect to nvidia.github.io:443 (185.199.111.153), connection timed out Could not connect to nvidia.github.io:443 (185.199.108.153), connection timed out Could not connect to
nvidia.github.io:443 (185.199.110.153), connection timed out Could not connect to
nvidia.github.io:443 (185.199.109.153), connection timed out`
`Err:10 https://nvidia.github.io/nvidia-container-runtime/ubuntu18.04/amd64  InRelease
Unable to connect to nvidia.github.io:https:`
`Err:11 https://nvidia.github.io/nvidia-docker/ubuntu18.04/amd64  InRelease
Unable to connect to nvidia.github.io:https:`

My system is : ubuntu 18.04
the **http_proxy** and **https_proxy** has been set.
the **apt** vision is 1.68
I had try
 `curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list |   sudo tee /etc/apt/sources.list.d/nvidia-docker.list`
and it return OK.

How could I solve this problem?

**Comment by nvjmayo** [comment]
For security reasons `http_proxy` and `https_proxy` are cleared when going through `sudo`. 
I confirmed this by running your 'curl' example through `sudo`, and saw that it also ignores the proxy settings. Example of ignored proxy settings:  `sudo curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
`

Recommend that you configure `apt.conf` for your proxy configuration in order to avoid having to manually pass `http_proxy` and `https_proxy` each time you want to use `apt`. For configuration information of `apt.conf` see [apt-transport-https(1)](http://manpages.ubuntu.com/manpages/cosmic/man1/apt-transport-https.1.html), [apt-transport-http(1)](http://manpages.ubuntu.com/manpages/cosmic/man1/apt-transport-http.1.html), and [apt-conf(5)](http://manpages.ubuntu.com/manpages/cosmic/man5/apt.conf.5.html)
