### ISSUE TITLE
nvidia docker not show result after dev_into 

### ISSUE THREAD

**Issue by Iqbalparvi** [NVIDIA/nvidia-docker#1096]
Hi Nvidia ,
when i run nvidia-smi before  dev_start  and after dev_into then i found the result :
 
![11111](https://user-images.githubusercontent.com/47267894/66353016-bc0b1380-e9ac-11e9-8835-6909cfecf81b.png)
kindly see where i do mistakes i am in great trouble due to this installation:
regards

**Comment by Mercy811** [comment]
- it seems that `docker/scripts/dev_into.sh` is [this](https://github.com/ApolloAuto/apollo/blob/master/docker/scripts/dev_into.sh).

if so, it uses `docker exec` which is used to interact with containers that are already running and run a command in this running container.  when you use it, you go inside into the container whose environment is separated from outside the container, in other words, your machine where you could  get the result before dev_into.sh as the first lines of the image.

- you can use `Nvidia-smi` because [it is installed when you install CUDA Driver](https://devtalk.nvidia.com/default/topic/1031644/in-what-step-is-nvidia-smi-supposed-to-be-installed-/)
- clink [here](https://github.com/NVIDIA/nvidia-docker) to see the structure of  docker containers leveraging NVIDIA GPUs. see the difference between **CUDA Toolkit** and **CUDA Driver**
