### ISSUE TITLE
command 'nvidia-smi' not found or does not exist  while running "nvidia/cuda" image

### ISSUE THREAD

**Issue by GBJim** [NVIDIA/nvidia-docker#113]
My seeting:
Ubuntu: 14.04 LTS
GPU: Tesla K80
Driver: 352.93
NVCC: V7.5.17

I followed the tutorial to install the nvidia-docker:
But when I run 
`nvidia-docker run --rm nvidia/cuda nvidia-smi`
It gives 
docker: Error response from daemon: Container command 'nvidia-smi' not found or does not exist..

But I can still run the bash of the image. When I run `nvidia-smi` in the containter, I get:
bash: nvidia-smi: command not found

**Comment by flx42** [comment]
You do have `nvidia-smi` on your host, right?

Can you also try the following?
```
ls -R `docker volume inspect -f "{{ .Mountpoint }}" nvidia_driver_352.93`
```

**Comment by 3XX0** [comment]
See your first issue for a fix

**Comment by agilmor** [comment]
Hi!

Not sure if my question is out-of-topic here... but at least the @flx42 comment is related to mine.

I've been reading the internals section because we are planning to use nvidia gpus in an HPC framework (based on slurm) and we want to avoid extra layers if we don't need them (not sure yet).
In our HPC we share the drivers version in all our nodes, so we can create our own launcher to add the necessary ```--device``` and ```-v``` related to drivers.
We don't want remote access or isolation because it is already handeled by slurm.
And probably the dockerfile inspection won't help us? (not sure)

Anyway, so far we already managed to make our GPUs available form the containers without adding any drivers to the containers (but using ```--device``` and ```-v```).
It worked with a basic ```debian:jessie``` container/image + cuda toolkit.

But I've just noted that the the ```nvidia/cuda``` image doesn't contain the ```nvidia-smi``` app?
Does it means that ```nvidia-docker``` is also mounting it fom the host?
Reading the the [volumes.go](https://github.com/NVIDIA/nvidia-docker/blob/064a148b7fdc148ee97a2b70619b13032e403c55/tools/src/nvidia/volumes.go#L118) it seems that I'm right, and that ```nvidia-docker``` also mount other ```nvidia-``` apps.

Is there any strong reason to do it?
As fas as i undertand, the ```nvidia-smi``` is not an static app, so it depends on host libs... and it could lead to problemes/incompatibilities between host/containers? (libc...?)
I expected only devices and user-space driver libs to be mounted?

Problably I'm missing somthing important here?

Thanks!

PS: If we finally add ```nvidia-docker``` to our toolchain (we would need to integrate it with slurm), at least we will have a deepr knowledge of this nice tool! ;-)

**Comment by 3XX0** [comment]
`nvidia-docker` works with slurm (we use it internally). What slurm isolation are you talking about? If it's `CUDA_VISIBLE_DEVICES` it's not true isolation and we actually make sure to unset is as it will cause issues. `nvidia-docker` provides true isolation through `NV_GPU`.

Binaries like `nvidia-smi` are tied to a specific driver version and mounted at runtime for portability reasons (as you guessed). Binary dependencies are mounted at runtime as well. libc has a stable ABI which is satisfied through the images/OS we support officially.

**Comment by agilmor** [comment]
Hi Jonathan,

nvidia-docker works with slurm (we use it internally).
>
Good to know!
Thanks!


> What slurm isolation are you talking about? If it's CUDA_VISIBLE_DEVICES
> it's not true isolation and we actually make sure to unset is as it will
> cause issues. nvidia-docker provides true isolation through NV_GPU.
>
We use the "gpu" type of GRES, and the isolation is managed by the
```File``` parameter.
An entry of our shared ```gres.conf```` looks as simple as this:
```
Nodename=c8 Name=gpu File=/dev/nvidia[0-5] Type=Maxwell Count=6
```

I thought it was using  ````cgroups``` internally and the
```devices.list``` controller...
But I've just checked it and it seems that you are right, it seems to be
using only the ```CUDA_VISIBLE_DEVICES```...? :-(
Until now (without docker) it has been isolating our jobs quite fine...
should we rethink it?

> Binaries like nvidia-smi are tied to a specific driver version
>
I see then... that's the reason I was looking for!
I though that ```nvidia-smi``` was a not-so-tied tool, i.e. compatible for
any drivers with a version higher than x.y, or something similar...

> and mounted at runtime for portability reasons (as you guessed).
>
Thanks for the info!

> Binary dependencies are mounted at runtime
>
Only the nvidia's drivers, right?
Not the libc or pthreads, right?

> as well. libc has a stable ABI which is satisfied through the images/OS we
> support officially.
>
So, for non officially supported images/OS (or if not using
```nvidia-docker``` my concerns about possible incompatibilities are more
or less correct, isn't it?


Thanks a lot for so quick and good answer!

**Comment by 3XX0** [comment]
> Until now (without docker) it has been isolating our jobs quite fine... should we rethink it?

Well this is up to you but your jobs can easily bypass this "isolation" and remember that `CUDA_VISIBLE_DEVICES` only affects CUDA so anything else (e.g. NVML) won't be isolated.

If I remember correctly (I would have to double check) running slurm with `nvidia-docker` is just a matter of doing something like:
`srun --gres=gpu:1 NV_GPU=$CUDA_VISIBLE_DEVICES nvidia-docker run --rm nvidia/cuda nvidia-smi`

> Only the nvidia's drivers, right?
Not the libc or pthreads, right?

That's right.

> So, for non officially supported images/OS (or if not using `nvidia-docker` my concerns about possible incompatibilities are more or less correct, isn't it?

If you are running some OS from ~2003 probably, you can check by yourself:
`objdump -p /usr/bin/nvidia-* | grep -E 'NEEDED|GLIBC'`
