### ISSUE TITLE
How to deal with docker compose?

### ISSUE THREAD

**Issue by romansavrulin** [NVIDIA/nvidia-docker#1152]
Did I get it right, according to https://github.com/docker/compose/issues/6691 it is recommended to use runtime arg, but it is deprecated in Nvidia-docker now. So how can one workaround this at the moment? I think it will be useful to provide some proven solution in readme here

**Comment by ggregoire** [comment]
Reading the last 2 comments, use `nvidia-container-runtime` instead of `nvidia-container-toolkit` (`nvidia-docker`).

**Comment by romansavrulin** [comment]
@ggregoire I've already came here with `nvidia-container-toolkit` and don't plan to came back to `nvidia-container-runtime` because it is deprecated. Aren't there any workaround for `nvidia-container-toolkit` ?

**Comment by RenaudWasTaken** [comment]
Hello!

Sorry for the huge lag on my part. We don't intend to remove nvidia-container-runtime until this issue is fixed. So for now the container-runtime is the way to go.

We've been working with the community on getting a better system in place, however as is always the case with efforts that require discussing with many projects things are slow (but steady).

I'll keep this thread open and update it when I have more information to communicate.

**Comment by romansavrulin** [comment]
looks like there's a workaround for now provided In https://github.com/docker/compose/issues/6691
