### ISSUE TITLE
Usage with Cuda 10

### ISSUE THREAD

**Issue by mertmerci** [NVIDIA/nvidia-docker#1153]
I want to use Docker with CUDA 10, is it enough to change the "cuda:9.0" sections under "Usage" like "$ docker run --gpus 2 nvidia/cuda:9.0-base nvidia-smi " with "cuda:10.0" ?

**Comment by dualvtable** [comment]
hi there,

To use CUDA 10, please ensure that you are running at least drivers >= 410.48 on Linux. Since you were running CUDA 9 containers, I wanted to point out that you need to have a newer driver on the host to be able to run CUDA 10 containers. 

CUDA and minimum driver versions are recorded in section 1 of the release notes: [https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#major-components](url)

To answer your original question (once the minimum driver dependency is met), you can replace "cuda:9.0" with "cuda:10.0" tags. 

Hope this helps!
