### ISSUE TITLE
How to run test nvidia-smi with rootless docker?

### ISSUE THREAD

**Issue by huyu398** [NVIDIA/nvidia-docker#1155]
My system is set up docker with [rootless mode](https://github.com/moby/moby/blob/ca5aab19b482f27629374cdde4df26b5676e39cb/docs/rootless.md).
I tried to install NVIDIA Container Toolkit by Quick start, and maybe it was successed.
But following error was occured to run test nvidia-smi with `docker run --gpus all nvidia/cuda:10.0-base nvidia-smi`.

> `docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running
hook: exit status 1, stdout: , stderr: nvidia-container-cli: mount error: open failed: /sys/fs/cgroup/devices/user.slice/devices.allow: permission denied\\\\n\\\"\"": unknown.
ERRO[0000] error waiting for container: context canceled`

It seems docker doesn't have permission to devices.allow because of rootless mode.
Is there some solutions?

#### Notice
My system is running behind porxy environmnent.
So rootless docker needs [some settings](https://github.com/docker/docker-install/issues/150), but maybe it is not relevant.

**Comment by krishnadasari610** [comment]
**command :** docker run -e NVIDIA_VISIBLE_DEVICES=all nvidia/cuda:9.0-base nvidia-smi
**output :** docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected\\\\n\\\"\"": unknown.
ERRO[0003] error waiting for container: context canceled 

Method 2 
**command**nvidia-docker run nvidia/cuda:9.0-base nvidia-smi
**output** 
docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: cuda error: no cuda-capable device is detected\\\\n\\\"\"": unknown.
ERRO[0002] error waiting for container: context canceled

**followed link:** 
https://github.com/NVIDIA/nvidia-docker
https://docs.nvidia.com/deeplearning/frameworks/user-guide/index.html#runcont

Please provide the resolution for this issue. 
![Screenshot from 2019-12-19 12-39-27](https://user-images.githubusercontent.com/19946280/71152538-aba0d000-225c-11ea-9130-94b432c35fe5.png)

**Comment by krishnadasari610** [comment]
When I use Dockerfile.ubuntu for my pc I am seeing the below issue. can someone provide the fix for the same.
![Screenshot from 2019-12-19 13-09-48](https://user-images.githubusercontent.com/19946280/71154446-8793bd80-2261-11ea-9e35-a800debadc1d.png)

Step 20/21 : RUN sed -i "s;@VERSION@;${REVISION};" debian/changelog &&     sed -i "s;@VERSION@;${PKG_VERS};" $DIST_DIR/nvidia-docker &&     if [ "$REVISION" != "$(dpkg-parsechangelog --show-field=Version)" ]; then echo "$(dpkg-parsechangelog --show-field=Version)" && exit 1; fi
 ---> Running in f3fc7672310d
dpkg-parsechangelog: warning:     debian/changelog(l1): version '-' is invalid: upstream version cannot be empty
LINE: nvidia-docker2 (-) UNRELEASED; urgency=medium
dpkg-parsechangelog: warning:     debian/changelog(l1): version '-' is invalid: upstream version cannot be empty
LINE: nvidia-docker2 (-) UNRELEASED; urgency=medium
unknown
The command '/bin/sh -c sed -i "s;@VERSION@;${REVISION};" debian/changelog &&     sed -i "s;@VERSION@;${PKG_VERS};" $DIST_DIR/nvidia-docker &&     if [ "$REVISION" != "$(dpkg-parsechangelog --show-field=Vadmin@test-Precision-5820-Tower:~/Desktop/BIO_Docker_Project/nvidia-docker-master$ returned a non-zero code: 1

**Comment by huyu398** [comment]
I resolved this problem myself.
The cause of this problem is that Rootless mode can't use cgroups, which is refered in [documents](https://docs.docker.com/engine/security/rootless/#known-limitations).
To avoid using cgroups for container i.e. Dockor is [here](https://github.com/containers/libpod/issues/3659#issuecomment-543912380).

@krishnadasari610 Is above patch helpful for you?

**Comment by djhshih** [comment]
We encountered the same error. To summarize, we had to edit `/etc/nvidia-container-runtime/config.toml` as follows:

```
[nvidia-container-cli]
no-cgroups = true
```

**Comment by leoribeiro** [comment]
> We encountered the same error. To summarize, we had to edit `/etc/nvidia-container-runtime/config.toml` as follows, in order to disable the use of cgroups by the NVIDIA container runtime, as noted above.
> 
> ```
> [nvidia-container-cli]
> no-cgroups = true
> ```

We still need to have access to root privileges in order to edit the file (`/etc/nvidia-container-runtime/config.toml`), right? Is there a way to avoid using cgroups without root access?
