### ISSUE TITLE
NPP libraries aren't mount for container with capabilities=compute 

### ISSUE THREAD

**Issue by rarzumanyan** [NVIDIA/nvidia-docker#1251]
This is a feature request issue.

### 1. Please add NPP libraries to nvidia/cuda:10.2 image
CUDA libraries are mounted within nvidia/cuda:10.2, but NPP libraries are not, despite that they are shipped with CUDA toolkit.

### 2. Repro:
```bash
docker run --gpus 'all,"capabilities=compute,utility,video"' -it nvidia/cuda:10.2-base /bin/bash
>find / -name libcuda.so
/usr/lib/x86_64-linux-gnu/libcuda.so
>find / -name libnpps.so
Not found
```

**Comment by zanbri** [comment]
Why was this closed? Is NPP now present in the container?

**Comment by flx42** [comment]
@zanbri since @rarzumanyan works at NVIDIA, I reached out to him to explain.

So, this is normal, NPP is a library that is not tied to your device driver version; hence it is not mounted from the host and instead should come from inside the container image.
You might want `nvidia/cuda:10.2-devel` or `nvidia/cuda:10.2-runtime` if you want NPP inside the container image.
