### ISSUE TITLE
What's the difference between the lastest nvidia-docker and nvidia container runtime？

### ISSUE THREAD

**Issue by chenyu-zhai** [NVIDIA/nvidia-docker#1268]
I saw an interesting blog.
[https://collabnix.com/introducing-new-docker-cli-api-support-for-nvidia-gpus-under-docker-engine-19-03-0-beta-release/](https://collabnix.com/introducing-new-docker-cli-api-support-for-nvidia-gpus-under-docker-engine-19-03-0-beta-release/)
After installing docker19.03, the blogger installed the docker container runtime instead of 
nvidia-docker. I feel very confused. 
Can you tell me the difference and connection between them?

**Comment by ai-starter** [comment]
I also find another project, it called nvidia container toolkit. 
I really confused now，which project should I choose when I create gpu environment？
@RenaudWasTaken

**Comment by klueska** [comment]
I originally posted a similar answer here, but hopefully this clears things up:
https://github.com/NVIDIA/k8s-device-plugin/issues/168#issuecomment-625981223

The set of packages collectively referred to as `nvidia-docker` consists of the following components (and their dependencies from top to bottom):

* `nvidia-docker2`
* `nvidia-container-runtime`
* `nvidia-container-toolkit`
* `libnvidia-container`

Unfortunately, the documentation across the repos that host code for these projects is inconsistent and misleading at times. Some places say that `nvidia-docker2` should no longer be installed for docker versions 19.03+ because it is deprecated, and you should only install `nvidia-container-toolkit` instead. Other places say that `nvidia-docker2` is required (even for docker versions 19.03+) if you plan on running Kubernetes on top of docker.

While both statements are technically true, I can see why things might be a little confusing.

Starting from the bottom, below is a description of what each of these components is responsible for:

`libnvidia-container`:
This package does the heavy-lifting of making sure that a container is set up to run with NVIDIA GPU support. It is designed to be `container-runtime` agnostic and provides a well-defined API and a wrapper CLI that different runtimes can invoke to inject NVIDIA GPU support into their containers.

`nvidia-container-toolkit`: 
This package includes a script that implements the interface required by a `runC` `prestart` hook. This script is invoked by runC after a container has been created, but before it has been started, and is given access to the `config.json` associated with the container (e.g. [this `config.json`](https://github.com/opencontainers/runtime-spec/blob/master/config.md#configuration-schema-example=)). It then takes information contained in the `config.json` and uses it to invoke the `libnvidia-container` CLI with an appropriate set of flags. One of the most important flags being which specific GPU devices should be injected into the container. 

`nvidia-container-runtime`:
This package used to be a complete fork of `runC` with NVIDIA specific code injected into it. Nowadays, it is a thin wrapper around the native `runC` installed on your machine. All it does is take a `runC` spec as input, inject the `nvidia-container-toolkit` script as a `prestart` hook into it, and then call out to the native `runC`, passing it the modified `runC` spec with that hook set. It's important to note that this package is not necessarily specific to docker (but it is specific to `runC`).

`nvidia-docker2`:
This package is the only docker-specific package of any of them. It takes the script associated with the `nvidia-container-runtime` and installs it into docker's `/etc/docker/daemon.json` file for you. This then allows you to run (for example) `docker run --runtime=nvidia ...`. It also installs a wrapper script around the native `docker` CLI called `nvidia-docker` which lets you invoke docker without needing to specify `--runtime=nvidia` every single time. It also lets you set an environment variable on the host (`NV_GPU`) to specify which GPUs should be injected into a container.

Given this hierarchy of components it's easy to see that if you only install `nvidia-container-toolkit` (which is recommended for docker 19.03+), then you will not get `nvidia-container-runtime` installed as part of it, and thus `--runtime=nvidia` will not be available to you. This is OK for Docker 19.03* because it calls directly out to `nvidia-container-toolkit` when you pass it the `--gpus` option instead of relying on the `nvidia-container-runtime` as a proxy.

In theory, you should never need `nvidia-container-runtime` or `nvidia-docker2` once upgrading to Docker 19.03. However, if you want to use Kubernetes with Docker 19.03, you actually need to continue using `nvidia-docker2` because Kubernetes doesn't support passing GPU information down to docker through the `--gpus` flag yet. It still relies on the `nvidia-container-runtime` to pass GPU information down the stack via a set of environment variables.

That said, there really isn't a whole lot to `nvidia-container-runtime` anymore. So you are basically running on the exact same stack as you would be whether you install `nvidia-docker2` or `nvidia-container-toolkit`, except that `nvidia-docker2 `will install a thin runtime that can proxy GPU information down to `nvidia-container-toolkit` via environment variables instead of relying on the `--gpus` flag to have Docker do it directly.

**Comment by loophole64** [comment]
@klueska 
Thank you very much! This cleared up a lot of confusion for me about the different packages.

**Comment by rtrobin** [comment]
@klueska Thank you so much for the clarification. I'm glad I run into this post. Can you please add this into nvidia official doc? For example, this [doc site](https://docs.nvidia.com/datacenter/cloud-native/contents.html)?

**Comment by elezar** [comment]
@rtrobin is your suggestion to update the content here https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/arch-overview.html#arch-overview with @klueska's descriptions above?

**Comment by rtrobin** [comment]
Basically, the doc([https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/arch-overview.html](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/arch-overview.html)) shown now is same as @klueska's post above. But the description here is more comprehensible to me, with different docker version and different docker parameters described. 

By the way, the driver containers overview doc([https://docs.nvidia.com/datacenter/cloud-native/driver-containers/overview.html](https://docs.nvidia.com/datacenter/cloud-native/driver-containers/overview.html)) is an independent tab. Maybe it could be part of architecture overview content([https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/arch-overview.html](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/arch-overview.html)), as a different way to utilize GPU?

**Comment by pejrich** [comment]
Hey Nvidia, I think you could be accused of a lot of things, but one thing I will **NEVER** accuse you of, is making developers lives easier.
