### ISSUE TITLE
Invalid symlink for libnvidia-opencl.so.1

### ISSUE THREAD

**Issue by whitespacer** [NVIDIA/nvidia-docker#1327]
### 1. Issue or feature description
Symlink for libnvidia-opencl.so.1 points for libnvidia-opencl.so.* from driver where build happened instead of driver for runtime system.

### 2. Steps to reproduce the issue
1. System where docker image is build has driver 450.36.06.
2. Base image for dockerfile is `nvidia/cudagl:10.2-devel-ubuntu16.04` 
3. Package ocl-icd-libopencl1 is installed. So docker file looks like
```docker
FROM nvidia/cudagl:10.2-devel-ubuntu16.04
RUN apt update \
         && apt install -y \
        ocl-icd-libopencl1
```
4. System where docker image is executed has driver 440.64.00
5. OpenCL doesn't work. Because of wrong symlink for `libnvidia-opencl.so.1`:
```
root@f29bf3634e18:/# ls -la /usr/lib/x86_64-linux-gnu/ | grep opencl
lrwxrwxrwx  1 root root       29 Jun  2 04:02 libnvidia-opencl.so.1 -> libnvidia-opencl.so.450.36.06
-rw-r--r--  1 root root 29182184 Feb 26 16:17 libnvidia-opencl.so.440.64.00
-rw-r--r--  1 root root 34465328 Jun  1 23:30 libnvidia-opencl.so.450.36.06
```

Note: OpenCL starts working after I manually change symlink. 

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [x] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
[nvidia-container_information.txt](https://github.com/NVIDIA/nvidia-docker/files/4812572/nvidia-container_information.txt)

 - [x] Kernel version from `uname -a`
4.4.0-177-generic
 - [ ] Any relevant kernel output lines from `dmesg`
 - [x] Driver information from `nvidia-smi -a`
440.64.00
 - [x] Docker version from `docker version`
19.03.8
 - [x] NVIDIA packages version from `dpkg -l '*nvidia*'` _or_ `rpm -qa '*nvidia*'`
ii  libnvidia-container-tools                     1.1.1-1                     amd64                       NVIDIA container runtime library (command-line tools)
ii  libnvidia-container1:amd64                    1.1.1-1                     amd64                       NVIDIA container runtime library
ii  nvidia-440                                    440.64.00-0ubuntu1          amd64                       NVIDIA binary driver - version 440.64.00
ii  nvidia-440-dev                                440.64.00-0ubuntu1          amd64                       NVIDIA binary Xorg driver development files

 - [x] NVIDIA container library version from `nvidia-container-cli -V`
1.1.1
 - [ ] NVIDIA container library logs (see [troubleshooting](https://github.com/NVIDIA/nvidia-docker/wiki/Troubleshooting))
 - [ ] Docker command, image and tag used

**Comment by klueska** [comment]
`libnvidia-opencl` is a driver specific library and will only run on the exact driver version it is installed with. For this reason, `nvidia-docker` will always inject the version of this library installed on whatever host your container is deployed on.

You should not attempt to install a different version of this library as part of the Docker image, or otherwise you will run into the type of issue you are seeing here.

If for some reason you require the `ocl-icd-libopencl1` library to be installed by the Docker image. You will need to need to manually do an `rm -f /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.1` later in the Dockerfile to allow the one that gets injected at runtime to take precedence (`nvidia-docker` will create the symlink to the correct library when it runs `ldconfig` before starting the container).
