### ISSUE TITLE
nvidia-docker command error

### ISSUE THREAD

**Issue by LW-SCU** [NVIDIA/nvidia-docker#1418]
error in this [page](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/user-guide.html#environment-variables-oci-spec)
![image](https://user-images.githubusercontent.com/28128257/99141071-1e3f4900-2682-11eb-83ba-24ae345d1254.png)

```bash
docker run --gpus '"device=1,2"' nvidia/cuda nvidia-smi --query-gpu=uuid --format-csv
```
```bash
docker run --gpus '"device=1,2"' nvidia/cuda nvidia-smi --query-gpu=uuid --format=csv
```

**Comment by klueska** [comment]
This is independent of `nvidia-docker` (i.e. you seem to have an issue with the output of the call to `nvidia-smi` under the hood).

That said, I don't see an issue in the output you are seeing. You only requested one field to be printed (uuid), so that is the only field you will get printed for each GPU. If you had requested more than one field (e.g. `--query-gpu=uuid,pci.bus_id,pci.domain`) then I would expect the following:

```
$ nvidia-smi --query-gpu=uuid,pci.bus_id,pci.domain --format=csv
uuid, pci.bus_id, pci.domain
GPU-edfee158-11c1-52b8-0517-92f30e7fac88, 00000000:06:00.0, 0x0000
GPU-f22fb098-d1b3-3806-2655-ba25f02229c1, 00000000:07:00.0, 0x0000
GPU-f613f823-1032-b3ec-a876-50f2e35e6f9e, 00000000:0A:00.0, 0x0000
GPU-3109fa37-4445-73c7-b695-1b5a4d13f58e, 00000000:0B:00.0, 0x0000
GPU-e28a6529-288c-7ddf-8fea-68c4833cda70, 00000000:85:00.0, 0x0000
GPU-a27fb382-bad2-c02a-95ba-f6a1da38e76c, 00000000:86:00.0, 0x0000
GPU-f5bb8d07-ee19-1787-4d9a-a84c4ac6b086, 00000000:89:00.0, 0x0000
GPU-1ba0ca0e-6d1d-d9db-07d8-c1c5a8c32814, 00000000:8A:00.0, 0x0000
```

**Comment by LW-SCU** [comment]
@klueska 
The `--format-csv` used on this [webpage](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/user-guide.html#environment-variables-oci-spec) instead of `--format=csv`, `--format-csv` is wrong.

**Comment by klueska** [comment]
@dualvtable Can you fix this documentation error?
