### ISSUE TITLE
Unable to use CUDA Versions below 11 when host has CUDA 11 Installed

### ISSUE THREAD

**Issue by ncoop57** [NVIDIA/nvidia-docker#1421]
### 1. Issue or feature description

My host machine has CUDA v11.0 and Driver v450.80.02. However, anytime I try and start a container with CUDA version below 11, like 10.2, the container ends up having the same CUDA version as the host. Are you only able to use CUDA versions that are above your host's?

### 2. Steps to reproduce the issue

Running the following command:
`docker run --rm --gpus all nvidia/cuda:10.2-base nvidia-smi`

Results in the following output:
```
Unable to find image 'nvidia/cuda:10.2-base' locally
10.2-base: Pulling from nvidia/cuda
171857c49d0f: Already exists 
419640447d26: Already exists 
61e52f862619: Already exists 
c118dad7e37a: Already exists 
29c091e4be16: Pull complete 
d85c81a4428d: Pull complete 
Digest: sha256:1774efa6e102a9bdfa393521c6b2254ea751dc1af9cff25c51376128bfb08d5e
Status: Downloaded newer image for nvidia/cuda:10.2-base
Sat Nov 21 22:11:43 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  A100-PCIE-40GB      Off  | 00000000:61:00.0 Off |                    0 |
| N/A   36C    P0    36W / 250W |      0MiB / 40537MiB |     30%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

which is the same output as running `nvidia-smi` from the host machine.

Any help would be greatly appreciated!

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [x] Some nvidia-container information: `nvidia-container-cli -k -d /dev/tty info`
```
NVRM version:   450.80.02
CUDA version:   11.0

Device Index:   0
Device Minor:   0
Model:          A100-PCIE-40GB
Brand:          Tesla
GPU UUID:       GPU-6b90bae5-cc31-b503-65ba-e3a4d2fb53eb
Bus Location:   00000000:61:00.0
Architecture:   8.0
I1121 22:18:29.259562 152260 nvc.c:337] shutting down library context
I1121 22:18:29.533601 152262 driver.c:156] terminating driver service
I1121 22:18:29.534247 152260 driver.c:196] driver service terminated successfully
```
 - [x] Kernel version from `uname -a`: 5.4.0-42-generic
 - [x] Docker version from `docker version`: `19.03.13`
 - [x] NVIDIA container library version from `nvidia-container-cli -V`: `1.3.0`

**Comment by klueska** [comment]
One of the primary functions of `nvidia-docker` is to inject the all of NVIDIA driver libs from the host into the container so that the container will run properly with GPUs.  One of these libraries is `libcuda.so`. This is one of the reasons you are seeing `nvidia-smi` report the driver version from your host.

The other reason is that the image you are running doesn't actually have any CUDA libraries installed in it.

It's actually fine to run an older version of CUDA on top of a newer version of `libcuda.so`, but that is not actually what you are doing here. The `nvidia/cuda:10.2-base` image does not have CUDA installed in it. As the name suggests, it is the `base` image for CUDA, which includes all of the prerequistes to install `cuda:10.2` on top of it (but doesn't actually include `cuda:10.2` itself).

The containers that actually contain CUDA are named as, e.g., `nvidia/cuda:10.2-runtime`, `nvidia/cuda:10.2-devel`, etc. Please see https://ngc.nvidia.com/catalog/containers/nvidia:cuda for more info.

**Comment by ncoop57** [comment]
Woah, that's pretty interesting. Thanks for the information!
