### ISSUE TITLE
The difference between MinorNumber and Index？

### ISSUE THREAD

**Issue by MonsterChen0430** [NVIDIA/nvidia-docker#1432]
I wanted to do some development based on nvml, but I don't understand that the difference between MinorNumber and Index.
Index is a parameter to nvmlDeviceGetHandleByIndex(), and MinorNumberis a parameter to nvmlDeviceGetMinorNumber().
In my opinion, Apart from the differences in type, they are almost equivalent.

**Comment by klueska** [comment]
For NVML, the most appropriate go-based project to reference is this:
https://github.com/NVIDIA/go-nvml

To answer your question though:
* Minor number is the actual `minor` number associated with the GPU device registered with the kernel. By convention, this is also the number appended to the file name for each device, e.g. `/dev/nvidia0`, `/dev/nvidia1`, etc. The minor number is assigned at boot time, when the PCIe device space is searched -- the first device encountered gets 0, the second gets 1, etc. It is *not* guaranteed to always be the same across reboots (but it usually is unless a new device is added).
* In contrast, *index* is just what the name implies -- the index of the GPU in the array tracking each of the GPU devices in the kernel. It is also represented by the order of the devices you see printed when you run `nvidia-smi`. On baremetal, the index will often be the same as the minor number since all GPUs are visible (this is not 100% guaranteed though). When running inside a container, however, the index will almost always be _different_ than the minor number (because we tend to limit the set of GPUs injected into a container and the minor numbers do not change). For example, we might inject only `/dev/nvidia0` and `/dev/nvidia3` into a container, but running, `nvidia-smi` will shows these as index 0 and 1.

With all of that said, the only reliable way to refer to a GPU and always be sure that you are getting the exact same GPU is to reference it by UUID, not minor number of index. So depending on what you are trying to do, this might be your preferred method.
