### ISSUE TITLE
stupid replace docker's config(daemon.json )，Instead of change it

### ISSUE THREAD

**Issue by forbxy** [NVIDIA/nvidia-docker#1448]
it is easy to parsing daemon.json and add runtimes section

**Comment by elezar** [comment]
Hi @forbxy. Thanks for creating the issue. Could you please expand this with a bit more detail as to what you see as the expected behavior? Examples are always useful.

**Comment by elezar** [comment]
@forbxy thanks for the additional info. Just to clarify, is what you describe **the behavior you want** or the behavior you are currently seeing and don't want?

**Comment by klueska** [comment]
The current behaviour is to save a backup of the existing `daemon.json` and put a new one in its place.
I think he's asking us modify the existing one instead of replacing it, so that the new one retains all of the old settings.

This is actually something we alraady do when updating the `daemon.json` file in the context of the GPU Operator:
https://gitlab.com/nvidia/container-toolkit/container-config/-/blob/master/src/docker.go

There are no concrete plans to add similar functionality directly to `nvidia-docker`, but it will likely be includes automatically in a rewrite of the entire `nvidia-container` stack that we will be rolling out in the next few months.

**Comment by forbxy** [comment]
@klueska yes,thank u

**Comment by klueska** [comment]
As I mentioned, we are not planning on updating this until we do our rewrite `nvidia-container` stack that we will be rolling out in the next few months. Closing this issue for now.
