### ISSUE TITLE
Error gathering devices info, lsat /dev/nvidia-uvm-tools: no such file

### ISSUE THREAD

**Issue by Anthony-Tatowicz** [NVIDIA/nvidia-docker#145]
After a reboot this error appears when trying to restart a container.

```
Error response from daemon: linux runtime spec devices: error gathering device information while adding custom device "/dev/nvidia-uvm-tools": lstat /dev/nvidia-uvm-tools: no such file or directory
Error: failed to start containers:
```  

```
Ubuntu: trusty
Driver Version: 352.93
CUDA: 7.5 (from apt)
```

**Comment by flx42** [comment]
Did you change your driver version recently?

**Comment by Anthony-Tatowicz** [comment]
Yes that was it, ill close this.

**Comment by DrChungAlbert** [comment]
I have the same issue
How to solve it ?

**Comment by mattsokoloff** [comment]
Problem:
My situation has been that when I use AWS gpu instances with docker the driver when I restart the machine. When this occurs I simply run the command to install the driver 'sudo apt-get install nvidia-<version>'. However, this makes it so that I can no longer run my docker container. No matter how much hacking I do, I cannot restore my instance. 

Solution (more of a recovery strategy):
-Create a new docker container. If it doesn't work then follow the advice here [https://github.com/NVIDIA/nvidia-docker/issues/288](url)
-From the host machine issue the following comand `sudo find -name / 'filesyouneed' 2>/dev/null`
(you could probably replace / with /var/lib/docker/aufs/mnt/ )
-Then copy all the files you need from the host to the docker `sudo docker cp /src [docker name]:/dest`

That should be it. It's hacky, but it works and you only lose about 15 minutes.

**Comment by koolaji** [comment]
```sudo nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml```
run this and everything will be ok
