### ISSUE TITLE
Creation of images with cuDNN{4,5}

### ISSUE THREAD

**Issue by christiantinauer** [NVIDIA/nvidia-docker#152]
When creating CentOS images (6 and 7), the statement in the cudnn Dockerfile avoids adding the libcudnn.so link. Is this done on purpose? See wildcard argument with ".\*" at the end instead of "\*":

```
RUN curl -fsSL http://developer.download.nvidia.com/compute/redist/cudnn/v5/cudnn-7.5-linux-x64-v5.0-ga.tgz -O && \
    echo "$CUDNN_DOWNLOAD_SUM  cudnn-7.5-linux-x64-v5.0-ga.tgz" | sha256sum -c --strict - && \
    tar -xzf cudnn-7.5-linux-x64-v5.0-ga.tgz -C /usr/local --wildcards 'cuda/lib64/libcudnn.so.*' && \
    rm cudnn-7.5-linux-x64-v5.0-ga.tgz && \
ldconfig
```

In Debian images the cuDNN libs are installed under /usr/lib/x86_64-linux-gnu/. Why not under /usr/local/cuda/lib64 as the other Cuda libs or as in CentOS images?

**Comment by flx42** [comment]
> When creating CentOS images (6 and 7), the statement in the cudnn Dockerfile avoids adding the libcudnn.so link. Is this done on purpose?

Yes, totally. But first of all, notice that this filtering is only done in the `runtime` version of the cuDNN image, compare:
https://github.com/NVIDIA/nvidia-docker/blob/master/centos-7/cuda/7.5/runtime/cudnn5/Dockerfile
https://github.com/NVIDIA/nvidia-docker/blob/master/centos-7/cuda/7.5/devel/cudnn5/Dockerfile

Then, look at those explanations by my colleague @3XX0 [here](https://github.com/tensorflow/tensorflow/issues/2525#issuecomment-223523008).
When using a runtime image of cuDNN, your code is already compiled (e.g. a deb or a pip package), so you don't need this symlink.

> In Debian images the cuDNN libs are installed under /usr/lib/x86_64-linux-gnu/. Why not under /usr/local/cuda/lib64 as the other Cuda libs or as in CentOS images?

Because we now have `.deb` packages for recent versions of cuDNN and they install at this location, which is the recommended locations for libraries installed through a deb package.
When installing a library without a deb, it should go in `/usr/local/`, CUDA is a bit particular since it's a deb that still installs in `/usr/local` for legacy reasons.

**Comment by christiantinauer** [comment]
Thank you very much for the explanation. With that information I can solve my problems now.

**Comment by jakirkham** [comment]
> Because we now have `.deb` packages for recent versions of cuDNN...

That's really neat. Are you guys planning on doing `.rpm` packages for Enterprise Linux?

**Comment by flx42** [comment]
@jakirkham I'm not aware of any plan for this, all deep learning frameworks primarily run on ubuntu.
Instead of RPMs, you can use the tarball, we do provide images with cuDNN on CentOS.
