### ISSUE TITLE
 OCI runtime create failed : mountpoint for devices not found

### ISSUE THREAD

**Issue by skychecker** [NVIDIA/nvidia-docker#1568]
Trying to install httpd on raspberry pi 4.
I followed instructions in description and got this error.

sky@Pi4:~$ docker run -dit --name my-apache-app -p 8080:80 -v "$PWD":/usr/local/apache2/htdocs/ httpd:2.4
Unable to find image 'httpd:2.4' locally
2.4: Pulling from library/httpd
eb9a2845ed12: Pull complete
f9908448c73e: Pull complete
d0855570c210: Pull complete
43334c8b7aeb: Pull complete
48d7bb40fabc: Pull complete
Digest: sha256:1d71eef54c08435c0be99877c408637f03112dc9f929fba3cccdd15896099b02
Status: Downloaded newer image for httpd:2.4
628ae154bb1cb1b709dd755401c61fd9faae0f7c7e58dfbdcef97f391a1c1602
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:385: applying cgroup configuration for process caused: mountpoint for devices not found: unknown.
sky@Pi4:~$

**Comment by elezar** [comment]
@skychecker could you describe the use case for nvidia-docker on a raspberry PI?

**Comment by skychecker** [comment]
> @skychecker could you describe the use case for nvidia-docker on a raspberry PI?

I have some study informations that were organized as html structure. So I need to host html server to be able to 
access them efficiently.

**Comment by elezar** [comment]
@skychecker the `nvidia-docker2` package and the NVIDIA Container Toolkit on which it depends are intended for use with NVIDIA GPUs.

Please uninstall the `nvidia-docker2` package and ensure that your `/etc/docker/daemon.json` does not reference the `nvidia-contianer-runtime` at all. You should then be able to use docker on you device.

I am closing this issue since it is not related to `nvidia-docker`'s intended use case. Please provide more information and reopen this if this is not the case.

**Comment by skychecker** [comment]
I'm a very newbie to this. Sorry for the inconveniences and thank you for the help.

**Comment by elezar** [comment]
No problem. I hope that this solves your problem.
