### ISSUE TITLE
No support for installing drivers on Rocky Linux 8.4

### ISSUE THREAD

**Issue by DeepikaKrishnaiah** [NVIDIA/nvidia-docker#1571]
### 1. Issue or feature description
No support for installing drivers on Rocky Linux 8.4
[](https://github.com/dellhpc/omnia/issues/664)
[#] (https://github.com/dellhpc/omnia/issues/664)
### 2. Steps to reproduce the issue
[](https://nvidia.github.io/nvidia-docker/) - The repository does not have support for Rocky 8

**Comment by andrewrech** [comment]
https://nvidia.github.io/nvidia-docker/rhel8.4/nvidia-docker.repo

works on Rocky 8.5

**Comment by elezar** [comment]
Hi @DeepikaKrishnaiah the NVIDIA CUDA driver is required to enable GPUs in containers, but is out of scope for `nvidia-docker` or any of the components of the NVIDIA Container Toolkit. If this issue is only related to getting the drivers installed (for which there seems to be workarounds), then please consider closing this issue.

If this issue is related to the installation of the components of the NVIDIA container stack (e.g. `nvidia-docker2` or `nvidia-container-toolkit`), then please provide more information here.

**Comment by justinmcdaniel** [comment]
For others coming here in present day on RHEL8 and derivatives other than CentOS8, you just need to override the $distribution variable to be "centos8" (sub version does not matter) when running the "setup the package repository and GPG key" in the official documentation.

This worked for me on RockyLinux 8.7.

**Comment by elezar** [comment]
Closing as resolved. Please see the updated [installation documentation](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html). And open an issue against https://github.com/NVIDIA/nvidia-container-toolkit if problems persist.
