### ISSUE TITLE
Conflict on daemon.json from nvidia-docker2 and docker

### ISSUE THREAD

**Issue by zmiimz** [NVIDIA/nvidia-docker#1575]
If I understand this correctly the user has to decide which daemon.json config file to use/overwrite, but this should be either mentioned somewhere in the installation guide
on the page  https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#install-guide or solved in a more elegant way using some package manager postscripts.
 

### 1. Issue or feature description
Conflict on daemon.json from nvidia-docker2-2.8.0-1.noarch (libnvidia-container)
and docker-20.10.11_ce-1.1.x86_64

zypper install -y nvidia-docker2
zypper: adjusting umask 077 of sudo-user term to 022 for user root.
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 4 NEW packages are going to be installed:
  libnvidia-container-tools libnvidia-container1 nvidia-container-toolkit nvidia-docker2

4 new packages to install.
Overall download size: 1.1 MiB. Already cached: 0 B. After the operation, additional 4.6 MiB will be used.
Continue? [y/n/v/...? shows all options] (y): y
Retrieving package libnvidia-container1-1.7.0-1.x86_64                                                                                                                       (1/4),  93.3 KiB (229.1 KiB unpacked)
Retrieving: libnvidia-container1-1.7.0-1.x86_64.rpm ........................................................................................................................................................[done]
Retrieving package libnvidia-container-tools-1.7.0-1.x86_64                                                                                                                  (2/4),  47.5 KiB (100.5 KiB unpacked)
Retrieving: libnvidia-container-tools-1.7.0-1.x86_64.rpm ...................................................................................................................................................[done]
Retrieving package nvidia-container-toolkit-1.7.0-1.x86_64                                                                                                                   (3/4), 966.9 KiB (  4.2 MiB unpacked)
Retrieving: nvidia-container-toolkit-1.7.0-1.x86_64.rpm ....................................................................................................................................................[done]
Retrieving package nvidia-docker2-2.8.0-1.noarch                                                                                                                             (4/4),  11.5 KiB ( 11.9 KiB unpacked)
Retrieving: nvidia-docker2-2.8.0-1.noarch.rpm ..............................................................................................................................................................[done]

Checking for file conflicts: ..............................................................................................................................................................................[error]
Detected 1 file conflict:

File /etc/docker/daemon.json
  from install of
     nvidia-docker2-2.8.0-1.noarch (libnvidia-container)
  conflicts with file from package
     docker-20.10.11_ce-1.1.x86_64 (@System)

File conflicts happen when two packages attempt to install files with the same name but different contents. If you continue, conflicting files will be replaced losing the previous content.
Continue? [yes/no] (no): no

Problem occurred during or after installation or removal of packages:
Installation has been aborted as directed.
History:
 - ABORT request: 

Please see the above error message for a hint.

**Comment by elezar** [comment]
Hi @zmiimz the current `nvidia-docker2` installation overwrites the `/etc/docker/daemon.json` file unconditionally (see also #1346). We are working on improving this experience by updating the file in place instead of overwriting it.

For the time being, I would recommend the following workaround:
1. install `docker-ce`
2. make a copy of `/etc/docker/daemon.json`
3. install `nvidia-docker2` and overwrite the `/etc/docker/daemon.json`
4. merge the two `daemon.json` files. (the only setting that `nvidia-docker2` requires is that `nvidia` be defined as the runtime.

I do agree that this could be better highlighted in the documentation.

**Comment by tomdaley92** [comment]
Hi there,
Currently I am not experiencing the described behaviour of `/etc/docker/daemon.json` being updated when I Install `nvidia-docker2` on Ubuntu 21.04 (latest nvidia-drivers and latest docker-ce installed). I found this issue because I was searching why that was not happening when the documentation stated that it will modify that file. Everything works correctly after I add the runtime block to the file manually but super confused why it isn't being updated like you claim it is.

It might be worth noting that I do add custom keys into my `/etc/docker/daemon.json` file BEFORE I install `nvidia-docker2`. Is there something in the implementation that detects an existing `/etc/docker/daemon.json` and leaves it unmodified if so?

It's kind of funny since before I found this issue I was already working on editing the file in place with Ansible (which sounds like is what you have plans to address soon anyways) 😄

I'm happy to give more information if it will help. I've reset my server to a clean snapshot and getting the same results every single time I go to test "redo" the install.

**Comment by elezar** [comment]
Hi @tomdaley92. The copy of `daemon.json` from the Debian package is specified in the following `.install` file: https://github.com/NVIDIA/nvidia-docker/blob/master/debian/nvidia-docker2.install and there is no specific logic to check whether it exists -- although the `dh_install` documentation is not quite clear on what the behaviour is in this case.

It could be that `dh_install` is failing to copy this file in which case your existing config is being maintained. Any logs around the installation to confirm this would be useful.

**Comment by tomdaley92** [comment]
Oh wow.. It was right under my nose the entire time :facepalm:

Yeah those default `dpkg options` would definitely explain it. Running `apt install -y nvidia-docker2` after blanking out the contents of `/etc/docker/daemon.json` does indeed prompt me about the configuration like you've shown for me.

```bash
automation@gpu:~$ sudo touch /etc/docker/daemon.json
automation@gpu:~$ sudo cat /etc/docker/daemon.json
automation@gpu:~$ sudo apt-get install -y nvidia-docker2
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libnvidia-container-tools libnvidia-container1 nvidia-container-toolkit
The following NEW packages will be installed:
  libnvidia-container-tools libnvidia-container1 nvidia-container-toolkit nvidia-docker2
0 upgraded, 4 newly installed, 0 to remove and 1 not upgraded.
Need to get 0 B/1,075 kB of archives.
After this operation, 4,747 kB of additional disk space will be used.
Selecting previously unselected package libnvidia-container1:amd64.
(Reading database ... 120630 files and directories currently installed.)
Preparing to unpack .../libnvidia-container1_1.7.0-1_amd64.deb ...
Unpacking libnvidia-container1:amd64 (1.7.0-1) ...
Selecting previously unselected package libnvidia-container-tools.
Preparing to unpack .../libnvidia-container-tools_1.7.0-1_amd64.deb ...
Unpacking libnvidia-container-tools (1.7.0-1) ...
Selecting previously unselected package nvidia-container-toolkit.
Preparing to unpack .../nvidia-container-toolkit_1.7.0-1_amd64.deb ...
Unpacking nvidia-container-toolkit (1.7.0-1) ...
Selecting previously unselected package nvidia-docker2.
Preparing to unpack .../nvidia-docker2_2.8.0-1_all.deb ...
Unpacking nvidia-docker2 (2.8.0-1) ...
Setting up libnvidia-container1:amd64 (1.7.0-1) ...
Setting up libnvidia-container-tools (1.7.0-1) ...
Setting up nvidia-container-toolkit (1.7.0-1) ...
Setting up nvidia-docker2 (2.8.0-1) ...

Configuration file '/etc/docker/daemon.json'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** daemon.json (Y/I/N/O/D/Z) [default=N] ?
```

Now, uninstalling nvidia-docker2, creating a blank '/etc/docker/daemon.json' file again and this time running with the dpkg options, gives:

```bash
automation@gpu:~$ sudo apt-get install -y -o Dpkg::Options::="--force-confold" nvidia-docker2
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libnvidia-container-tools libnvidia-container1 nvidia-container-toolkit
The following NEW packages will be installed:
  libnvidia-container-tools libnvidia-container1 nvidia-container-toolkit nvidia-docker2
0 upgraded, 4 newly installed, 0 to remove and 1 not upgraded.
Need to get 0 B/1,075 kB of archives.
After this operation, 4,747 kB of additional disk space will be used.
Selecting previously unselected package libnvidia-container1:amd64.
(Reading database ... 120630 files and directories currently installed.)
Preparing to unpack .../libnvidia-container1_1.7.0-1_amd64.deb ...
Unpacking libnvidia-container1:amd64 (1.7.0-1) ...
Selecting previously unselected package libnvidia-container-tools.
Preparing to unpack .../libnvidia-container-tools_1.7.0-1_amd64.deb ...
Unpacking libnvidia-container-tools (1.7.0-1) ...
Selecting previously unselected package nvidia-container-toolkit.
Preparing to unpack .../nvidia-container-toolkit_1.7.0-1_amd64.deb ...
Unpacking nvidia-container-toolkit (1.7.0-1) ...
Selecting previously unselected package nvidia-docker2.
Preparing to unpack .../nvidia-docker2_2.8.0-1_all.deb ...
Unpacking nvidia-docker2 (2.8.0-1) ...
Setting up libnvidia-container1:amd64 (1.7.0-1) ...
Setting up libnvidia-container-tools (1.7.0-1) ...
Setting up nvidia-container-toolkit (1.7.0-1) ...
Setting up nvidia-docker2 (2.8.0-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
automation@gpu:~$
```

What's a little concerning to me now is that when I go to uninstall `nvidia-docker2` with `apt purge` it looks like its trying to remove the entire `/etc/docker` directory and removes the `/etc/docker/daemon.json` file along with it? I feel like that file should never be deleted by this package, and would break docker installation on the machine. I realize I can uninstall the `nvidia-docker2` package without using `apt purge` which leaves the configuration files in place. However this seems like a file that only the `docker-ce` package should remove. Any thoughts?

```bash
automation@gpu:~$ sudo apt purge nvidia-docker2
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libnvidia-container-tools libnvidia-container1 nvidia-container-toolkit
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  nvidia-docker2*
0 upgraded, 0 newly installed, 1 to remove and 1 not upgraded.
After this operation, 27.6 kB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 120654 files and directories currently installed.)
Removing nvidia-docker2 (2.8.0-1) ...
(Reading database ... 120649 files and directories currently installed.)
Purging configuration files for nvidia-docker2 (2.8.0-1) ...
dpkg: warning: while removing nvidia-docker2, directory '/etc/docker' not empty so not removed
automation@gpu:~$ sudo rm /etc/docker/daemon.json
rm: cannot remove '/etc/docker/daemon.json': No such file or directory
```

and thank you by the way, I really appreciate you taking the time to look at this 👍🏼

**Comment by elezar** [comment]
Yes, you're right in that the `nvidia-docker2` package should most likely not "provide" the `daemon.json` file in the way that it does. This is one of the things that we're looking to change by having this file modified by a post-installation trigger or by the user instead of requiring that it be defined as part of the package. 

There is a bit of scaffolding that we need to get in place for that to be possible, but hope to get it out sometime in the near future.

**Comment by jbcpollak** [comment]
Just wanted to chime in that we were bitten by the purge problem today and it took a long while to hunt down - we have scripts to install nvidia drivers and docker support, and the first thing it does to make sure everything is good is to purge all previous installations and then reinstall (with --force-confold, which sent me down a rabbit hole for a while). Separately we provide our own daemon.json with logging customizations. When we re-install nvidia-docker2, surprise! your logging changes have been removed.

For now I'll switch to remove instead of purge, but I'd like to request `apt purge nvidia-docker2` please leave docker/daemon.json file were it is - especially since it seems that having the nvidia-specific configs in the daemon file seem to do no harm on non-nvidia computers or with the drivers not installed.

**Comment by klueska** [comment]
Instead of pulling in the `nvidia-docker2` package, I would recommend pulling in `nvidia-container-toolkit` as the top-level package and then running:

``` 
$ sudo nvidia-ctk runtime configure --runtime=docker [--set-as-default]
$ sudo systemctl restart docker
```

This has the same effect as pulling in the `nvidia-docker2` package except that it reads / modifies docker`s `daemon.json file to add the `nvidia-container-runtime` (and optionally make it the default runtime), leaving all other options in tact.

**Comment by jbcpollak** [comment]
> Instead of pulling in the `nvidia-docker2` package, I would recommend pulling in `nvidia-container-toolkit` as the top-level package and then running:

Thanks @klueska - this works well. I was afraid the nvidia-container-toolkit was the "old" way to install docker support.

**Comment by klueska** [comment]
Not at all -- `nvidia-docker2` is in the process of being deprecated in favor of the procedure I just described.

**Comment by Kunzol** [comment]
From experience I know, it is always a bad idea to poke in config files of other packages. 

I use `jq` for updating `daemon.json`. But I just cover simple changes.  To make it "foolproof" it is quiet complex. 

Better would be to have in docker a subdirectory e.g. `daemon.d` where all additional config files go in and are merged in order of file name. This might not even be done inside docker. A `ExecStartPre` script in systemd might work, too.

**Comment by elezar** [comment]
With the v1.14.0 release of the NVIDIA Contianer Toolkit, the `nvidia-docker2` package no longer includes `config.json` and the recommended mechanism for updating this config file is to use the
```
nvidia-ctk runtime configure
```
command: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#configuring-docker

Also not that the `nvidia-docker2` package is now considered deprecated and it is suggested that the `nvidia-container-toolkit` package be installed directly.

If there are still problems with this, please open an issue against https://github.com/NVIDIA/nvidia-container-toolkit.
