### ISSUE TITLE
Couldn't open CUDA library libcudnn.so when using docker image

### ISSUE THREAD

**Issue by Haffi112** [NVIDIA/nvidia-docker#160]
I'm new to tensorflow but I'm trying to get the docker image to run without issues. I have installed nvidia drivers, cuda-8.0 and cuDNN.

When I run 

    nvidia-docker run -it -p 8888:8888 gcr.io/tensorflow/tensorflow:latest-gpu

and if I run the third notebook, then I get the following error message:

    I tensorflow/stream_executor/dso_loader.cc:99] Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:
    I tensorflow/stream_executor/cuda/cuda_dnn.cc:1562] Unable to load cuDNN DSO

I'm running Ubuntu 16.04 and I have a single nvidia 1070 card. I'm not sure if this is a problem with my install or a problem with the docker image. Any help would be appreciated.

**Comment by flx42** [comment]
It was a problem with TensorFlow when looking for libcudnn at runtime, I believe it was fixed by this commit:
https://github.com/tensorflow/tensorflow/pull/3091

The version of TensorFlow on gcr.io is rather old (`0.8.0`), I advise you to use the following image instead: `tensorflow/tensorflow:nightly-gpu`

By the way, you don't need CUDA 8.0 or cuDNN on the host, you only need the driver. The rest will be inside the container.
