### ISSUE TITLE
gcc 5.3+

### ISSUE THREAD

**Issue by jendap** [NVIDIA/nvidia-docker#167]
/usr/local/cuda/include/host_config.h:115 contains:

#if __GNUC__ > 5 || (__GNUC__ == 5 && __GNUC_MINOR__ > 3)
#error -- unsupported GNU version! gcc versions later than 5.3 are not supported!
#endif /* __GNUC__ > 5 || (__GNUC__ == 5 && __GNUC_MINOR__ > 1) */

Too bad! Ubuntu xenial-updates has 5.4! See http://packages.ubuntu.com/search?keywords=gcc&searchon=names&suite=xenial-updates&section=all

That means `nvidia/cuda:8.0-cudnn5-devel-ubuntu16.04` is not easy to use. One can't even run "apt-get update && apt-get upgrade" :(

How about checking just major version since 5.x are all bugfix versions of 5.

**Comment by jendap** [comment]
workaround:

sudo sed -i -e 's/__GNUC_MINOR__ > [0-9]/__GNUC_MINOR__ > 666/g' /usr/local/cuda/include/host_config.h

**Comment by flx42** [comment]
We are aware of this problem, that's why I didn't update the 16.04 images recently, to avoid ending up with a broken image.

According to the Docker "best practices", you should avoid doing `apt-get upgrade` in a container anyway :)
https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/apt-get
Is this a problem? Why do you need to do an upgrade?

Anyway, we are going to release a small fix for CUDA soon. If that helps, our compiler team told us that removing the `GNUC_MINOR` check is safe (**for this version only**).

**Comment by jendap** [comment]
There are different philosophies ... some reasoning may prefer running upgrade other may try avoid it ...

This is obviously a bug in the cuda header file. Minor versions in gcc 5.x are bugfix versions. Gcc team is doing decent job. We can trust them we are better of with the bugfix version. I think the header file should not check compiler at all (or have a warning in the worst case).

BTW: The docker best practices recommends to talk to base image maintainers if there is obsoleted package in the base image. We would end up here anyway :-)

**Comment by flx42** [comment]
The compiler check is important because nvcc heavily relies on gcc. 

> Minor versions in gcc 5.x are bugfix versions.

Yes, because gcc changed strategy for 5.X I believe. In 4.X, minor version changes were more important.

> The docker best practices recommends to talk to base image maintainers if there is obsoleted package in the base image. We would end up here anyway :-)

True :) But I was curious if you were faced with a bug that required gcc 5.4 or another updated package. Hopefully, this problem will be fixed on Monday.

**Comment by flx42** [comment]
@jendap please test the new image!
