### ISSUE TITLE
 Can not start nvidia-docker command remotely.

### ISSUE THREAD

**Issue by knimi** [NVIDIA/nvidia-docker#171]
I tried to remotely deploy containers on gpu instance of Amazon EC2 from my mac book air(OSX) and followed the procedure(https://github.com/NVIDIA/nvidia-docker/wiki/Deploy-on-Amazon-EC2#container-deployment), but failed at the final step. 
```
$ nvidia-docker run --rm nvidia/cuda nvidia-smi
-bash: nvidia-docker: command not found
```
I have already checked that my machine become active host because docker command is found. 

Also, after connecting to the ec2 machine by ssh, 
I confirmed nvidia-docker command can be successfully called. 
```
$ nvidia-docker ssh aws01 
ubuntu@aws01:~$ sudo nvidia-docker run --rm nvidia/cuda nvidia-smi
# this is ok 
```
It seems to be wrong to install nvidia-docker to my laptop according to the issue(#130)
Do you know how to let Docker daemon to know the nvidia-docker command?

**Comment by 3XX0** [comment]
We don't support Mac OSX at the moment.
Your best chance is to use `docker` and query the `nvidia-docker` restapi (see [here](https://github.com/NVIDIA/nvidia-docker/wiki/Internals)]

**Comment by flx42** [comment]
You need to install `nvidia-docker` on the client machine, but it won't work because you have Mac OS. The goal here is to retrieve the right arguments for the remote machine, e.g. arguments in the form `--device=... --volume=...`. It's possible to use `docker` instead of `nvidia-docker` using the REST API of our daemon. For instance, locally:
```
$ curl -s http://localhost:3476/docker/cli
--device=/dev/nvidiactl --device=/dev/nvidia-uvm --device=/dev/nvidia3 --device=/dev/nvidia2 --device=/dev/nvidia1 --device=/dev/nvidia0 --volume-driver=nvidia-docker --volume=nvidia_driver_361.48:/usr/local/nvidia:ro
$ docker run -ti --rm `curl -s http://localhost:3476/docker/cli` nvidia/cuda nvidia-smi
```
See our [wiki](https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker-plugin#rest-api)

To retrieve those arguments remotely, you have two options.

1) Use something similar than what @amacneil suggested, by using a `curl` container to retrieve the arguments from the remote machine..
```
export DOCKER_HOST=mybox
docker run -ti `docker run --net=host --rm centos curl -s http://localhost:3476/docker/cli` nvidia/cuda
```

2) Modify the `nvidia-docker-plugin` service to make it listen on a different address, because by default it listens on `localhost:3476`. For instance, on ubuntu 14.04 with upstart:
```
# On my laptop:
$ curl http://mybox:3476/docker/cli
curl: (7) Failed to connect to titanboxmch port 3476: Connection refused
# didn't work because the REST listens on localhost by default

# On machine "mybox":
$ sudo emacs /etc/default/nvidia-docker
# add "-l 0.0.0.0:3476" to listen for any incoming connection.
$ sudo restart nvidia-docker

# On my laptop:
curl -s http://mybox:3476/docker/cli
--volume-driver=nvidia-docker --volume=nvidia_driver_361.77:/usr/local/nvidia:ro --device=/dev/nvidiactl --device=/dev/nvidia-uvm --device=/dev/nvidia-uvm-tools --device=/dev/nvidia3 --device=/dev/nvidia2 --device=/dev/nvidia1 --device=/dev/nvidia0
```

**WARNING**: be careful with EC2, only do that if you know what you are doing, you do not want to expose the REST API to the whole world. You probably want to setup proper security groups to only authorize connection from trusted IPs:
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/authorizing-access-to-an-instance.html

**Comment by flx42** [comment]
@3XX0 suggested that the best option is to use a ssh tunnel, he's right. You already have ssh access to the remote machine.

Quick and dirty version:
```
# On my laptop
$ curl http://localhost:3476/docker/cli
# Doesn't work, nvidia-docker is not running locally.
$ ssh -f -N -L 3476:localhost:3476 mybox
$ curl -s http://localhost:3476/docker/cli
--volume-driver=nvidia-docker --volume=nvidia_driver_361.77:/usr/local/nvidia:ro --device=/dev/nvidiactl --device=/dev/nvidia-uvm --device=/dev/nvidia-uvm-tools --device=/dev/nvidia3 --device=/dev/nvidia2 --device=/dev/nvidia1 --device=/dev/nvidia0
# Now it works!
```

**Comment by juharris** [comment]
For anyone else that ends up here, now that it's using `systemd`, I had to change the `ExecStart` line in `/etc/systemd/system/multi-user.target.wants/nvidia-docker.service` since it doesn't use `NVIDIA_DOCKER_PLUGIN_OPTS` from `/etc/default/nvidia-docker`. So now I have:
```
ExecStart=/usr/bin/nvidia-docker-plugin -s $SOCK_DIR -l 0.0.0.0:3476
```

Then I did `sudo service nvidia-docker restart` and it was fine.
