### ISSUE TITLE
libcudnn.so not installed under /usr/local/cuda/lib in nvidia/cuda:7.5-cudnn5-devel

### ISSUE THREAD

**Issue by davidzchen** [NVIDIA/nvidia-docker#172]
We recently upgraded our Docker images to `nvidia/cuda:7.5-cudnn5-devel` for the TensorFlow GPU CI build. We noticed that in the new image, `libcudnn.so` is installed under `/usr/lib/x86_64-linux-gnu` rather than `/usr/local/cuda/lib64`. Is this expected? If so, what is the motivation for installing `libcudnn.so` in a directory separate from the other CUDA libraries?

Here is our Dockerfile: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/Dockerfile.gpu

+cc @gunan @jendap @martinwicke

**Comment by flx42** [comment]
Yes that's normal because we use a `deb` package for cudnn now, and the deb package installs in the right place. CUDA is still in `/usr/local/cuda
See: https://github.com/NVIDIA/nvidia-docker/issues/168#issuecomment-238924455 and the comment below

**Comment by davidzchen** [comment]
Understood. Thanks for the explanation!

**Comment by flx42** [comment]
To be clear: you should support both paths. For some cases we have to install cuDNN with a tarball and thus we install to `/usr/local/cuda`. For instance we do that on CentOS because we don't have rpms for cuDNN, or for CUDA 8.0 because we don't have the debs yet: https://github.com/NVIDIA/nvidia-docker/blob/master/ubuntu-14.04/cuda/8.0/runtime/cudnn5/Dockerfile#L9-L13

**Comment by davidzchen** [comment]
Got it. I actually have cuDNN installed under `/usr/local/cuda` on my workstation, and my original assumption that this was the standard install directory for cuDNN. I'll make sure that both cases are supported and tested. Thanks for your help!
