### ISSUE TITLE
Problems in exporting an image.

### ISSUE THREAD

**Issue by divamgupta** [NVIDIA/nvidia-docker#174]
I have  a container which is running perfectly.  But when I export the container using a `nvidia-docker export`and reimport in on the same host or another host, it doesn't work properly.

Commands like nvidia-smi and nvcc are not found.
Also the folder `/usr/local/nvidia`becomes empty in the exported image.

**Comment by flx42** [comment]
Using `docker export`, you lose all the layers of the image and therefore you lose all the labels, `nvidia-docker` relies on that to detect if an image is a GPU application, see our [wiki](https://github.com/NVIDIA/nvidia-docker/wiki/Image-inspection).

>  Also the folder /usr/local/nvidia becomes empty in the exported image.

This is because `docker export` can't handle volumes, this is not specific to `nvidia-docker`.

Instead of `docker export`, you should use `docker commit` and then `docker save` instead. You will keep the history of the image.

**Comment by divamgupta** [comment]
I tried committing, saving then loading the image. 

`nvidia-smi` still is missing but `nvcc` is working. Whereas nvcc wasn't working with export.

I did a docker inspect and the label  `"com.nvidia.volumes.needed": "nvidia_driver"` is present.

I am using  image  `nvidia/cuda` .

**Comment by flx42** [comment]
> I tried committing, saving then loading the image. 
> `nvidia-smi` still is missing but `nvcc` is working

I've taken a look and something is definitely wrong here, could be a nvidia-docker or docker bug, I will investigate some more.

> Whereas nvcc wasn't working with export.

Again, this is because you are losing all the environment, so you lost the `PATH` variable that is pointing at `/usr/local/cuda/bin`. nvcc is still here.

**Comment by flx42** [comment]
Ok, so there is something weird about the permissions but unless you try to delete the volume created by `nvidia-docker`, it should not be a problem for you. I filed an issue against Docker here: https://github.com/docker/docker/issues/25854, we'll see.

For instance, the following works fine for me, repeatedly:
```
nvidia-docker run -ti --name test nvidia/cuda sh -c 'nvcc --version && echo hello > /foo.txt'
docker export test -o exported.tar
docker rm test
docker rmi nvidia/cuda
docker import exported.tar test-imported
nvidia-docker run --rm -ti test-imported sh -c 'nvcc --version && cat foo.txt'
```

However, if I try to remove the volume, all hell breaks loose:
```
$ docker volume rm nvidia_driver_361.77
Error response from daemon: Error while removing volume nvidia_driver_361.77: remove nvidia_driver_361.77: VolumeDriver.Remove: internal error, check logs for details
```
Since the volume was improperly removed, we only have the folders left in the volume, the binaries and libs are gone:
```
$ ls -l /var/lib/nvidia-docker/volumes/nvidia_driver/361.77/bin/
total 0
```

**Comment by 3XX0** [comment]
Closing, it should now work with 2.0/master

**Comment by mashuiping** [comment]
nvidia-docker save work for me to reuse docker images on the other computer
