### ISSUE TITLE
Unable to load cuDNN DSO - Missing Symlink? 

### ISSUE THREAD

**Issue by dshieble** [NVIDIA/nvidia-docker#205]
Hi! I think that nvidia-docker is awesome, and it's been super useful for me. 

I am working on an ubuntu machine with 4 GeForce GTX TITAN X cards and I am using the gcr.io/tensorflow/tensorflow:latest-gpu image that the tensorflow team maintains.

When I run the python mnist convolutional test with `python -m tensorflow.models.image.mnist.convolutional`, I see a "Unable to load cuDNN DSO" error. I can fix this error by creating a symlink between /usr/lib/x86_64-linux-gnu/libcudnn.so.4 and /usr/lib/x86_64-linux-gnu/libcudnn.so with the command `ln -s /usr/lib/x86_64-linux-gnu/libcudnn.so.4 /usr/lib/x86_64-linux-gnu/libcudnn.so`. I believe that this is a similar issue to https://github.com/NVIDIA/nvidia-docker/issues/45. Is there a more permanent way to fix this problem?

**Comment by flx42** [comment]
So, this is not a `nvidia-docker` bug, TensorFlow used to open the unversioned symlink, which was incorrect. See here: https://github.com/tensorflow/tensorflow/issues/2525#issuecomment-223523008

They now fixed it, but you are still seeing this issue because gcr.io has a very old version of TensorFlow (0.8.0). See here: https://github.com/tensorflow/tensorflow/issues/3669

Instead, you should use TensorFlow from the DockerHub: `tensorflow/tensorflow:0.10.0-devel-gpu`
However, you can't use a more recent version than that like `tensorflow/tensorflow:nightly-devel-gpu` because of another issue: https://github.com/tensorflow/tensorflow/issues/4363
(but the fix for this one is easy, just modify `LD_LIBRARY_PATH`).
