### ISSUE TITLE
Installation for "Other distributions" doesn't support CUDA 8.0

### ISSUE THREAD

**Issue by Fengyboy** [NVIDIA/nvidia-docker#210]
I have a docker image built for `CUDA 7.5` and `cuDNN 5`, however today when I was trying to rebuild the image using the same `dockerfile`, I got the following error:
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://developer.download.nvidia.com  Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F60F4B3D7FA2AF80

So I changed the dockerfile with respect to `CUDA 8.0` and `cuDNN 5.1`, and the docker image was successfully built. When I try to run it on an AWS instance with Amazon Linux via `nvidia-docker`, it raises  the following error:
Error: unsupported CUDA version: driver 7.5 < image 8.0 Failed to run Docker container: nvidia-docker | 2016/09/30 14:42:48 Error: unsupported CUDA version: driver 7.5 < image 8.0.

After comparing the installation instructions, I realised the package has been updated to `rc3.1` for both `Ubuntu` and `CentOS` but not for `Other distributions`. It appears that `rc3.1` has added the support for `CUDA 8.0`.

So my questions are when the `CUDA 7.5` server can be fixed and when the installation for `Other distributions` can be updated to `rc3.1`. Many thanks in advance.

**Comment by flx42** [comment]
> 
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://developer.download.nvidia.com Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F60F4B3D7FA2AF80

Sorry about that, this is because the signing keys changed in our repos. New versions of the containers will be pushed soon.

> Error: unsupported CUDA version: driver 7.5 < image 8.0 Failed to run Docker container: nvidia-docker | 2016/09/30 14:42:48 Error: unsupported CUDA version: driver 7.5 < image 8.0.

This is simply because your driver is too old to run CUDA 8.0 code, this is not because of nvidia-docker. You should install driver 367 or stick to CUDA 7.5.

>  It appears that rc3.1 has added the support for CUDA 8.0.

Nope, it's just a driver version problem.

Also, regarding CUDA 8.0, it's still the RC version right now, the final version of CUDA 8.0 will be published very soon.

**Comment by flx42** [comment]
New CUDA 8.0 images has been pushed and you shouldn't see any key issue with the repo now. Closing.

**Comment by mikecouk** [comment]
Hashtag excellent news ! Thanks !

**Comment by yeison** [comment]
I'm seeing the same public key issue with 7.5 devel:

W: GPG error: http://developer.download.nvidia.com  Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F60F4B3D7FA2AF80

**Comment by flx42** [comment]
@yeison do  you have the latest version of the image? Did you try a `docker pull`?
