### ISSUE TITLE
Verify cuDNN

### ISSUE THREAD

**Issue by haoyangz** [NVIDIA/nvidia-docker#251]
Hi thanks a lot for the great work!

I built my own Keras-docker image from nvidia/cuda:8.0-cudnn5-runtime-ubuntu14.04 . But when I run Keras in it, it doesn't show that it is using cudnn, which does happen every time I run out side of docker. I wonder if there is a way to verify that cudnn is installed and working?

Thanks!

**Comment by flx42** [comment]
It seems to be a problem from your Dockerfile or from Keras.  You configuration is incorrect or Keras doesn't look for cuDNN at the right place.

**Comment by haoyangz** [comment]
Hm, actually I think theano (the backend of Keras) didn't even find the GPUs. Because normally it will report sth like this when I do `import theano`
```
Using gpu device 0: Tesla K40c (CNMeM is enabled with initial size: 10.0% of memory, cuDNN 5005)
```

But now I got nothing, even the **`Using gpu device 0: Tesla K40c `** part. But I do get correct output when I do `nvidia-smi` showing the GPUs.  A related question is I can't do `nvcc` either. Maybe I am missing something here about how to run nvidia-docker?

**Comment by flx42** [comment]
You don't have `nvcc` because you have a `-runtime` image, it doesn't include the CUDA toolkit, but it includes all the libraries for compiling prebuilt CUDA code.
Theano is a bit tricky since it JITs the code at execution time so I believe it needs `nvcc` indeed.
Try using `nvidia/cuda:8.0-cudnn5-devel-ubuntu14.04` as a base instead.

**Comment by haoyangz** [comment]
Yes, using `devel` image instead of `runtime` resolves the problem. Thanks a lot!
