### ISSUE TITLE
libcuda.so* behavior is inconsistent?

### ISSUE THREAD

**Issue by itamaro** [NVIDIA/nvidia-docker#276]
I'm trying to build a Docker image directly from ubuntu:14.04 (not based on the nvidia-provided images), and when I run it with `nvidia-docker` I can't find `libcuda.so* anywhere.

IIUC, nvidia-docker is supposed to bind-mount libcuda.so (and friends) at runtime.

Here's what I checked with the nvidia-provided cuda-runtime image:

```
# nvidia-docker - I see libcuda.so*
$ nvidia-docker run -it --rm nvidia/cuda:8.0-runtime find / -name libcuda*
/usr/local/nvidia/lib64/libcuda.so.1
/usr/local/nvidia/lib64/libcuda.so.367.48
/usr/local/nvidia/lib64/libcuda.so
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudart.so.8.0.44
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudart.so.8.0

# plain docker - no libcuda.so
$ docker run -it --rm nvidia/cuda:8.0-runtime find / -name libcuda*
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudart.so.8.0.44
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudart.so.8.0
```

So I expect that this would work the same with my custom image, or even the base ubuntu:14.04 image - but it doesn't:

```
$ nvidia-docker run -it --rm ubuntu:14.04 find / -name libcuda*
# no results
```

am I missing anything?

**Comment by flx42** [comment]
Hello,

Since `nvidia-docker` is a drop-in replacement for `docker`, we wanted our tool to be no-op for images that are clearly not GPU images, like the base `ubuntu` image.
`nvidia-docker` only mounts `libcuda.so` if the image has the label `com.nvidia.cuda.version`.
This is explained on our [wiki](https://github.com/NVIDIA/nvidia-docker/wiki/Image-inspection#nvidia-docker).

**Comment by itamaro** [comment]
Gotcha. Missed that detail in the wiki. Thanks.
