### ISSUE TITLE
How to check the driver version of image

### ISSUE THREAD

**Issue by wakanawakana** [NVIDIA/nvidia-docker#361]
I would like to use a container that is open to dockerHub etc.
However, problems often arise with the nvidia docker execution machine and the nvidia driver version used to create the image.
For example, K520 can be used in the instance of EC2, but the official driver is 367.57
In MXNet(docker pull dmlc/mxnet:cuda), it is created with a newer driver, and the following error occurs.
”CUDA: CUDA driver version is insufficient for CUDA runtime version”

How can I align the image creation environment with the execution environment?

**Comment by flx42** [comment]
First of all, looks like the MXNet image on DockerHub is one year old, you shouldn't use it. Build your own image from their Dockerfile instead.

>  the nvidia driver version used to create the image.

There is no such thing, actually. Our images don't contain any driver file. The CUDA version that is used in a Dockerfile dictates the minimum driver version required for execution, see our [wiki](https://github.com/NVIDIA/nvidia-docker/wiki/CUDA#requirements). But, with 367.57 you should be able to run CUDA 7.5 and CUDA 8.0 code, and `dmlc/mxnet:cuda` is CUDA 7.5.
So it looks like the issue is somewhere else, please try with a newer mxnet image, then provide your exact steps.

**Comment by wakanawakana** [comment]
Thank you for your polite reply.
Problems have not occurred in most images.
Normally, it is created from "nvidia/cuda:xxx" using the necessary base image.
I found that "dmlc/mxnet:cuda" is suspicious..

Thank you very much.
