### ISSUE TITLE
NVIDIA Grid Support

### ISSUE THREAD

**Issue by bivanecon** [NVIDIA/nvidia-docker#478]
Is it possible to use nvidia grid technology with nvidia-docker? i.e "split" NVIDIA's GPU to several vGPUs, and use such vGPUs inside containers.

**Comment by cliffwoolley** [comment]
CUDA does not support this kind of virtualization in the way that graphics
does -- only pass-through.  But anyway that's for VMs, and here we're
talking about containers.

You can use the same GPU from multiple processes simultaneously with CUDA
in a time-sliced manner(*), but there's presently not a way to constrain
how much of the GPU's resources (memory, SMs, time slices, etc.) any one of
them takes up.

Sorry,
Cliff


On Sep 23, 2017 5:24 AM, "bivanecon" <notifications@github.com> wrote:

Is it possible to use nvidia grid technology with nvidia-docker? i.e
"split" NVIDIA's GPU to several vGPUs, and use such vGPUs inside containers.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NVIDIA/nvidia-docker/issues/478>, or mute the thread
