### ISSUE TITLE
Ubuntu 17.10 support

### ISSUE THREAD

**Issue by defunctzombie** [NVIDIA/nvidia-docker#507]
Opening this issue to gage or get an estimate on adding ubuntu 17.10 support to the build process.

I was able to make the 2.0 branch of this repo (and the container runtime) repo build for 17.10 with some minor changes. The main things that I tweaked were the name and targeted docker-ce version which for some reason is hard-coded in the makefile instead of provided as a floating range.

**Comment by flx42** [comment]
For the docker dependency, it's intended: https://github.com/NVIDIA/nvidia-docker/issues/502#issuecomment-338266943

**Comment by flx42** [comment]
Are the packages provided for 16.04 incompatible with 17.10?

**Comment by defunctzombie** [comment]
> Are the packages provided for 16.04 incompatible with 17.10?

Yea. I had to package it myself using 17.10 as the docker image base because the current provided packages had a dependency on file-rc and sysv-rc neither of which are available in 17.10.

BTW, I am running against docker-ce 17.10 using Ubuntu 17.10. I now realize how confusing all these version numbers are. Anyhow, the only gotcha I had with the debs I tried was the sysv-rc/file-rc dependencies.

**Comment by flx42** [comment]
> the current provided packages had a dependency on file-rc and sysv-rc neither of which are available in 17.10.

This is true for nvidia-docker 1.0, branch 2.0 should not have this issue: `apt-get install -y nvidia-docker2`.

> I am running against docker-ce 17.10 using Ubuntu 17.10. I now realize how confusing all these version numbers are.

Yes, it is confusing :). We don't support edge releases of Docker for now, as explained in #502.

**Comment by 3XX0** [comment]
Closing, this should be addressed in 2.0/master.

**Comment by cy94** [comment]
@defunctzombie Can you please help me setup nvidia-docker 2.0 on Ubuntu 17.10? I am building with Docker 1.13.1. I changed the base image from ubuntu:xenial to ubuntu:artful and ran the Makefile for this specific Docker version, the build completed successfully and generated the "nvidia-docker" executable. However, nvidia-docker hasn't been installed globally. Are there any other commands that I have to run?

**Comment by darrylbobo** [comment]
@cy94 : any luck with install nvidia-docker 2.0 on ubuntu 17.10??

**Comment by cy94** [comment]
@darrylbobo Yes, I got it to work. You need to build these packages from source - 
- https://github.com/NVIDIA/libnvidia-container
- https://github.com/nvidia/nvidia-container-runtime
- https://github.com/NVIDIA/nvidia-docker

Change the Makefile wherever required - keep only xenial for Docker 1.13.1 (or whichever version you have) and remove other versions 

- libnvidia-container
  - docker build --build-arg USERSPEC=$(id -u):$(id -g) -t libnvidia-container:ubuntu -f Dockerfile.ubuntu .
  - docker run --rm -v /my/output/directory:/mnt libnvidia-container:ubuntu
  - Change the output directory path to the one you want
  - install the libnvidia-container-* .deb packages in the output directory using "sudo dpkg -i package.deb"
- nvidia-container-runtime
  - sudo make
  - install the deb package in dist/
- nvidia-docker
  - sudo make
  - move nvidia-docker to /usr/bin
  - add nvidia-docker executable to $PATH or as an alias
- [Register the nvidia runtime](https://github.com/nvidia/nvidia-container-runtime#docker-engine-setup) using only one of the methods

Hope this helps!

**Comment by flx42** [comment]
Didn't the xenial packages work?

**Comment by cy94** [comment]
@flx42 I couldn't install with apt-get because I couldn't add the apt-get sources.

**Comment by flx42** [comment]
@cy94 You mean the repository? What was the error message?

**Comment by cy94** [comment]
@flx42 Sorry for the delay, apt-get update ignored the repository/sources after I followed the instructions [here](https://github.com/NVIDIA/nvidia-docker). This is the error - 

Ign:27 https://nvidia.github.io/libnvidia-container/ubuntu16.04/amd64  InRelease                                                                      
Ign:28 https://nvidia.github.io/nvidia-container-runtime/ubuntu16.04/amd64  InRelease
Ign:29 https://nvidia.github.io/nvidia-docker/ubuntu16.04/amd64  InRelease
Err:30 https://nvidia.github.io/libnvidia-container/ubuntu16.04/amd64  Release
  Could not handshake: Error in the pull function.
Err:31 https://nvidia.github.io/nvidia-container-runtime/ubuntu16.04/amd64  Release
  Could not handshake: Error in the pull function.
Err:32 https://nvidia.github.io/nvidia-docker/ubuntu16.04/amd64  Release
  Could not handshake: Error in the pull function.
Reading package lists... Done               
W: GPG error: http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu artful InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY FCAE110B1118213C

This might be because I'm running apt-get update behind a proxy at work.
