### ISSUE TITLE
Any gpu-resource-monitor manager tools for multi-users?

### ISSUE THREAD

**Issue by ysh329** [NVIDIA/nvidia-docker#513]
I have some problems when multi-users using docker. Because of root privilege for each one in his/her own container, if you use `top` or `gpustat` command to loop up gpu-use-situation out of container, they all show the root user is using gpu.

Thus, I wanna ask:
1. how to show use status of gpu for each person?
2. how to isolation of GPU resources for each person?

Thanks in advance~ 😀

**Comment by flx42** [comment]
You can run Docker containers as a user with something like `docker run -ti -u $(id -u):$(id -g) ubuntu`. In addition, you can isolate which GPUs will be available using `-e NVIDIA_VISIBLE_DEVICES=0,1` with nvidia-docker 2.0. Or with environment variable `NV_GPU` for 1.0.

Showing the right GPU status is a bit more tricky, inside the container you will only see the GPUs you have access to with `nvidia-smi`, but you won't see the running processes because `nvidia-smi` doesn't support containers.

**Comment by ysh329** [comment]
Thanks my big brother! 😍

**Comment by ysh329** [comment]
@flx42 eh, a little problem Again, bother you
```shell
$ docker run -ti -u $(id -u):$(id -g) ubuntu
groups: cannot find name for group ID 1002
I have no name!@e2b172837076:/$
```

**Comment by flx42** [comment]
This is not an issue from `nvidia-docker`, it's because the user doesn't exist inside the container.
