### ISSUE TITLE
Can nvidia-docker run support mounting driver without mounting device (e.g. /dev/nvidia0)

### ISSUE THREAD

**Issue by hongshibao** [NVIDIA/nvidia-docker#583]
When I use Kubernetes with GPU suppport, I want the Pod can only see the GPU cards that are allocated by Kubernetes. Currently I found that by default docker containers could see all GPU cards in a host if I used nvidia-docker run.
Does nvidia-docker support only mounting driver for containers, and let Kubernetes scheduler mount the devices (e.g. /dev/nvidia0) ?

**Comment by flx42** [comment]
You can use `NVIDIA_VISIBLE_DEVICES=none`.
https://github.com/nvidia/nvidia-container-runtime#nvidia_visible_devices

But it's probably because you are launching a CUDA image without specifying a GPU resource, right?
I also have a fix for the next release, setting `NVIDIA_VISIBLE_DEVICES` to the empty string (e.g. `NVIDIA_VISIBLE_DEVICES=`) will prevent nvidia-docker from doing anything.

**Comment by RenaudWasTaken** [comment]
Hello!

> Does nvidia-docker support only mounting driver for containers, and let Kubernetes scheduler mount the devices (e.g. /dev/nvidia0) ?

I don't think your are using the recommended solution for using GPUs in Kubernetes.
You are now expected to use device plugins and should use the [nvidia device plugin](https://github.com/NVIDIA/k8s-device-plugin/tree/v1.9) you will then need to request `nvidia.com/gpu` in your pod spec.

**Comment by hongshibao** [comment]
Yes, I use nvidia device plugin. The nvidia-docker2 and nvidia device plugin are installed in my hosts. I also enable GPU support (Accelerators=true) and device plugin support (DevicePlugins=true) for my k8s env. The default runtime is set to use nvidia too.
After that, a pod, which requests one GPU and runs a container with cuda9 installed, can be allocated to one host with 4 GPUs. But I find that now all 4 GPUs are visible inside the container. What I hope is that the container should only see one GPU which is allocated by k8s (i.e. devices mounted by k8s).

**Comment by flx42** [comment]
This doesn't seem right, are you running your pod as `privileged`?

**Comment by pineking** [comment]
@hongshibao I think the correct solution is

1. install nvidia-docker2 and nvidia device plugin
2. set DevicePlugins=true, and do not set Accelerators=true
3. use `nvidia.com/gpu` in yaml file instead of `alpha.kubernetes.io/nvidia-gpu`

I test it, and it works well.
you should not use the old way (Accelerators=true + `alpha.kubernetes.io/nvidia-gpu`) with nvidia-docker2 together.

**Comment by hongshibao** [comment]
@flx42 No, they were not running as privileged.
@pineking Got it! I will try again and give you the feedback. Thanks.

**Comment by xmm1989218** [comment]
@pineking my env must use cuda 8.0 but nvidia device plugin will use cuda 9.0. is there any solution for this?

**Comment by pineking** [comment]
what's the mean of "nvidia device plugin will use cuda 9.0"?  AFAIK, CUDA is built in your docker images, which is independent of device plugin. I think both of them can work correctly with device plugin.

**Comment by xmm1989218** [comment]
@pineking 不好意思 我发现你是中国人 我英语不太好 用英语表述比较吃力 是这样子的 碰到了这issue提供者一样的问题 但我一开始其实用的nvidia-docker2+k8s-device-plugin 主机上装的cuda是8.0 然后业务的tensorflow也是用的cuda 8.0 然后就碰到了说cuda的一个啥函数找不到 然后我看了k8s-device-plugin的Dockerfile 我看到cuda 9.0我以为是因为这个不兼容 于是我就尝试了不用k8s-device-plugin改成nvidia-docker2+alpha.kubernetes.io/nvidia-gpu这种方式 然后容器就正常跑起来了 但是碰到提issue的人一样的问题 k8s中limit 1但是容器中却可以看到所有的GPU

**Comment by pineking** [comment]
@xmm1989218 your question is not the case of this issue, so we can close this issue here.
I can help you to solve the problem. we can discuss the more details using wechat  (wechat: pineking)

**Comment by flx42** [comment]
Thanks for the help @pineking!
