### ISSUE TITLE
Where is nvcc inside nvidia/caffe?

### ISSUE THREAD

**Issue by Mottotime** [NVIDIA/nvidia-docker#59]
I can not find nvcc inside the nvidia/caffe image.

Would you please add it into the image and provide some explanation of how nvidia-docker works? Because I find it little mysterious to understand how nvidia-docker talks to host GPU device.

Besides, I suggest installing caffe with source code. Because examples of caffe and cuda are valuable tools for beginners.

Thank you very much.

**Comment by moconnor725** [comment]
nvcc is the compiler.  Once caffe is built you wouldn't need the compiler any more.  

nvidia docker enables applications that can talk to the driver to run in a container by mapping the driver into the environment.

The nvidia/caffe container isn't really meant as a substitution for a shell environment.  It's not a virtual machine.  The nvidia/caffe image is available for users to build upon (like DIGITS) or for users who want to execute a caffe command in a container (like caffe train).

**Comment by flx42** [comment]
You can find more information on the wiki, especially this page:
https://github.com/NVIDIA/nvidia-docker/wiki/Why%20NVIDIA%20Docker#motivation

**Comment by flx42** [comment]
@moconnor725 is right. To elaborate a bit more: we cannot foresee all possible use cases so we decided to provide a limited number of images for Caffe and DIGITS. For CUDA we have many combinations (base OS + version + runtime/devel + cudnn version) but that's OK since that's the base image.
Caffe is useful as a base image for far less people that CUDA, so we didn't want to do the same (e.g.: base OS + cudnn version + caffe version + source/no-source). If your particular use case is different then you can either build on top of the existing Caffe image (and `apt-get` nvcc) or on top of the cudnn image and build Caffe from source. You can take a look at the Dockerfile for BVLC/caffe (**not** NVIDIA/caffe) for the latter:
https://github.com/BVLC/caffe/blob/master/docker/standalone/gpu/Dockerfile

**Comment by thu814** [comment]
Thank you very much, @moconnor725 @flx42 :)

As a user, I need a full development environment of CUDA and Caffe inside docker because I want to quickly build, test and deploy my model in a consistent environment. I think it would be convenient to begin with CUDA and Caffe examples to test the hardware/software environment.

I will take @flx42 's suggestions and build a container based on these Dockerfiles.

Again, thank you for your kind explanation and advices.

**Comment by Mottotime** [comment]
Thank you very much, @moconnor725 @flx42 :)

As a user, I need a full development environment of CUDA and Caffe inside docker because I want to quickly build, test and deploy my model in a consistent environment. I think it would be convenient to begin with CUDA and Caffe examples to test the hardware/software environment.

I will take @flx42 's suggestions and build a container based on these Dockerfiles.

Again, thank you for your kind explanation and advices.
