### ISSUE TITLE
Selinux Permission update on nvidia drivers

### ISSUE THREAD

**Issue by dllehr81** [NVIDIA/nvidia-docker#627]
Hi All,
  I just wanted to check in.  I noticed a change in later driver rpms on RedHat/Centos.  When nvidia-docker is creating volumes for new drivers, it's loading them in an selinux group that prohibits docker from sharing with a running container.

For example.  
```
ls -Z /var/lib/nvidia-docker/volumes/nvidia_driver/
drwxr-xr-x. nvidia-docker nvidia-docker system_u:object_r:svirt_sandbox_file_t:s0 384.81
drwxr-xr-x. nvidia-docker nvidia-docker system_u:object_r:xserver_var_lib_t:s0 387.36
```

Docker requires the `svirt_sandbox_file` label by default, unless otherwise specified, and for some reason we are now seeing volumes being created with the `xserver_var_lib`

Do you know of any issues that are causing this?  Does nvidia-docker 2.0 alleviate this problem?  We are currently running `nvidia-docker-1.0.1-1` on RedHat 7.4

**Comment by 3XX0** [comment]
There is not much we can do here. Until we have LSM namespaces, changing the labels is too risky as it might break the host (e.g. Xorg). So it's usually the responsibility of the administrator to write a policy that allows such use case.

Having said that, 2.0 seems to work on Centos 7.4 with the default profiles (see `semanage fcontext -l  | grep -E 'nvidia|cuda'`). Make sure you `restorecon` the driver files though because sometimes they might carry the wrong labels after the install.

**Comment by 3XX0** [comment]
See also https://github.com/NVIDIA/nvidia-container-runtime/issues/28
