### ISSUE TITLE
Document what the code does

### ISSUE THREAD

**Issue by therc** [NVIDIA/nvidia-docker#67]
I was reading the plugin code to figure how to best access it from Kubernetes (or from a Kubernetes daemon). I noticed that there aren't many comments or any READMEs explaining what's going on. E.g. just figuring what exactly goes into a volume requires jumping from package to package. This doesn't need to be in the top-level end user documents or even the wiki, as most people won't care about internals, but it'd be nice to have in the source tree.

Would you accept PRs with READMEs and comments?

**Comment by 3XX0** [comment]
Sure, feel free to PR documentation if you think that some part of the code deserve more explanation

**Comment by matthieudelaro** [comment]
Thanks to nvidia-docker I trained neural network very easily in containers, with an OS version different than the host. Really helpful. 

So now I am interested in documentation as well, to figure out how to use nvidia-docker-plugin from [Nut](https://github.com/matthieudelaro/nut). The goal is to mount nvidia devices in container, in order to allow users of deep learning frameworks to train their models. (I target only linux users here, since it seems like there is no hope yet to mount GPUs in the VM of Docker for Mac.)

Nut doesn't rely on docker cli, but interacts with docker host directly. I would like to do the same with nvidia-docker-plugin. As far as I understand from the code, provided that nvidia-docker-plugin daemon is running, all I need it to reproduce the behavior of `nvidia-docker run`? 

Which would correspond to the end of [tools/src/nvidia-docker/main.go](https://github.com/NVIDIA/nvidia-docker/blob/master/tools/src/nvidia-docker/main.go):
```go

   if (command == "create" || command == "run") && opt != "" {
		vols, err := VolumesNeeded(opt)
		assert(err)

		if vols != nil {
			var nargs []string
			var err error

			if Host != nil {
				nargs, err = GenerateRemoteArgs(opt, vols)
			} else {
				assert(nvidia.LoadUVM())
				assert(nvidia.Init())
				nargs, err = GenerateLocalArgs(opt, vols)
				nvidia.Shutdown()
			}
			assert(err)
			args = append(args[:off], append(nargs, args[off:]...)...)
		}
	}

	assert(docker.Docker(args...))
```

I guess I don't need to create volumes, discover devices, etc... because all of this is handle by the plugin, right?

**Comment by 3XX0** [comment]
Your use case seems related to #39 but to answer your question, yes everything is handled by the plugin.

**Comment by 3XX0** [comment]
We added more thorough documentation in the section [internals](https://github.com/NVIDIA/nvidia-docker/wiki/Internals)

**Comment by matthieudelaro** [comment]
When mounting the devices in the container with Docker API, one has to specify cgroup permissions. It work on my desktop with the following value `CgroupPermissions: "mrw"`, but what would be the recommended value?

**Comment by 3XX0** [comment]
You need read/write/mknod permissions.
In practice though, Docker seems to ignore the mknod one (mknod succeeds even without it).
