### ISSUE TITLE
Pulling repository docker.io/library/cuda Error:image library/cuda not found

### ISSUE THREAD

**Issue by alfredox10** [NVIDIA/nvidia-docker#69]
Trying to build the ubuntu 14.04 caffe dockerfile but it keeps saying that it can't pull library/cuda. This is the link to the dockerfile I'm trying to build locally.

https://github.com/NVIDIA/nvidia-docker/blob/master/ubuntu-14.04/caffe/Dockerfile

This is the command I'm using:
nvidia-docker build -t alfredox10/bibsmart .

I have already done the volume setup
sudo nvidia-docker volume setup

Anyone have any idea why this is happening? I googled it, but there is no info available since this is pretty new.

**Comment by flx42** [comment]
Building the caffe image locally requires you to first build the CUDA image locally.
You have two options:
1) Build the cuda image locally using the makefile: `make -C ubuntu-14.04/cuda 7.0-cudnn4-runtime`
2) Modify the Dockerfile to use the image we provide on the DockerHub:
`FROM nvidia/cuda:7.0-cudnn4-runtime` instead of `FROM cuda:7.0-cudnn4-runtime`

**Comment by alfredox10** [comment]
Awesome that worked man, I feel like this wasn't made very clear in the documentation at all. Specially for those that are new to Docker.

**Comment by 3XX0** [comment]
https://github.com/NVIDIA/nvidia-docker/wiki/Building-images-locally
