### ISSUE TITLE
Will there be Docker EE support?

### ISSUE THREAD

**Issue by CC-Hsu** [NVIDIA/nvidia-docker#695]
Hi,

As far as I know, Docker CE and Docker EE engine do not differ too much.

Will nvidia-docker release also provide supported packages (e.g. RPMs) for Docker EE?

Thanks.

**Comment by mpanthofer** [comment]
I am just getting into supporting our ML/AI teams (this is really great stuff). So I am proposing to add an nvidia-docker node to our docker ee2 bare metal cluster running on centos 7 rather than turning them loose on AWS GPUs. I plan to create some Tensorflow base images for our teams to use as a springboard. As I see it, there are 2 questions I need to work through: 1)  Will nvidia-docker install and work as expected in docker ee2 cluster, and 2) will our customers (we are a Docker partner) accept a non-certified plugin/container for GPU workloads on a docker ee platform? Assuming that answer to question 1 is "yes" - I'll have to let you know about the feedback to question 2 after I start presenting it to enterprise customers. 

If you have any suggestions for my journey or new development, please let me know. Otherwise I'll keep you posted as I make some progress.

**Comment by flx42** [comment]
>  1) Will nvidia-docker install and work as expected in docker ee2 cluster

I don't know, we do not test this configuration. If there are issues, I can still try to look at it with the information you will provide us.

> 2) will our customers (we are a Docker partner) accept a non-certified plugin/container for GPU workloads on a docker ee platform

We can't answer this question :)
Docker doesn't certify this kind of runtime plugin. Nor does the OCI.
