### ISSUE TITLE
Missing Centos7 / Amazon Linux YUM repos

### ISSUE THREAD

**Issue by theatrus** [NVIDIA/nvidia-docker#708]
The underlying repositories pointed to by the install instructions have gone missing.

Specifically:

https://nvidia.github.io/nvidia-docker/centos7/x86_64/nvidia-docker.repo
https://nvidia.github.io/nvidia-docker/amzn2/x86_64/nvidia-docker.repo

Both leads to repositories which don't exist, like:

https://nvidia.github.io/nvidia-docker/centos7/x86_64/

**Comment by flx42** [comment]
Can you be more specific?

The installation instructions should now send you to this file, for Amazon linux 2:
https://nvidia.github.io/nvidia-docker/amzn2/nvidia-docker.repo
The instructions have been udpated recently to remove the `x86_64`, since the arch can be encoded in the repo file itself.

> Both leads to repositories which don't exist, like:
https://nvidia.github.io/nvidia-docker/centos7/x86_64/

This repo does exist, you just can't browse it this way:
https://github.com/NVIDIA/nvidia-docker/tree/gh-pages/centos7

**Comment by theatrus** [comment]
```[root@227ba19e8ec7 yum.repos.d]# dnf update
Failed to synchronize cache for repo 'libnvidia-container', disabling.
```

Looks like our bootstrap was using the $basearch bootstrap, which was refusing to do anything with the repository. 

Using the new install version has fixed it, thanks!

**Comment by theatrus** [comment]
And to add more some data, we were actually hitting this issue:

https://bugzilla.redhat.com/show_bug.cgi?id=1566988

Which is not a repository issue (and an upstream issue) - thanks for the help!
