### ISSUE TITLE
nvidia-docker vs nvidia-docker-plugin ?

### ISSUE THREAD

**Issue by earcz** [NVIDIA/nvidia-docker#727]
**Hi Everyone,**

While I was trying to start implementing [nvidia-jetson/redtail](https://github.com/NVIDIA-Jetson/redtail/wiki/Testing-in-Simulator) project, I have encountered the term of **"docker"**. For a few days, I am trying to understand docker and nvidia-docker, and about to grasp. However, I have still some questions about nvidia-docker. I am eager to hear response from you. Thanks in advance.

1. I need to install **nvidia-docker v1** for redtail project. **(I have installed it before but messed the system by mistake so that I reinstalled my OS (Ubuntu 16.04) again.** After installation nvidia-docker v1, I have also seen that there is an another term which is **nvidia-docker-plugin**. I could not get the idea behind of it. Is **nvidia-docker-plugin** something that I should install after installing nvidia-docker? If the answer is no, is nvidia-docker itself enough to use GPU in docker? If the answer is yes, what is the nvidia-docker-plugin exactly?

2. I might be confused with the docker concept since it is new to me as a mechanical engineer. According to implement deep learning and other applications (control etc.) for my project, I need to install Cuda, cuDNN, Caffe, DIGITS and so on. Do I have to install them in docker? or Do I just **pull** or **run** them while running nvidia-docker or docker? I think I will not install them, e.g. CUDA, since they will be pulled from the **hub.docker**. Is that right? if not, what is the right answer for this question?

Kind regards, Ender.

**Comment by flx42** [comment]
> I need to install nvidia-docker v1 for redtail project. (I have installed it before but messed the system by mistake so that I reinstalled my OS (Ubuntu 16.04) again. After installation nvidia-docker v1, I have also seen that there is an another term which is nvidia-docker-plugin. I could not get the idea behind of it. Is nvidia-docker-plugin something that I should install after installing nvidia-docker? If the answer is no, is nvidia-docker itself enough to use GPU in docker? If the answer is yes, what is the nvidia-docker-plugin exactly?

nvidia-docker-plugin was a daemon necessary for nvidia-docker v1. If you install the v1 package, the nvidia-docker-plugin will get automatically started and a `nvidia-docker` binary will also be installed.
But I encourage you to try with nvidia-docker v2,  if you follow the current instructions on our README, that's what you will install.

> According to implement deep learning and other applications (control etc.) for my project, I need to install Cuda, cuDNN, Caffe, DIGITS and so on. Do I have to install them in docker?

You can write a Dockerfile to build an image with all the dependencies that you need. You can use our CUDA images on DockerHub as the base, for instance `FROM nvidia/cuda:9.0-devel-ubuntu16.04`.

>  Do I have to install them in docker? or Do I just pull or run them while running nvidia-docker or docker?

If there is already a published image with everything that you want, you can just do `docker pull` or `docker run`. Otherwise, you will need to extend our CUDA images.
