### ISSUE TITLE
can not start docker after restart the computer

### ISSUE THREAD

**Issue by liuliyalei** [NVIDIA/nvidia-docker#787]
ubuntu 16.04
Nvidia-docker
I can not start docker, does anyone know why?

![qq 20180709142111](https://user-images.githubusercontent.com/40382579/42434146-8b86a966-8384-11e8-8c53-d1f403ce37e0.png)
![qq 20180709141729](https://user-images.githubusercontent.com/40382579/42434158-9011ae68-8384-11e8-87dd-61a0449f06aa.png)

**Comment by LeitchP** [comment]
I'm getting the same behaviour.  I completely removed docker (and I mean completely), then started installing step by step. Everything was working with repeated restarts until I installed NVidia-Docker 2

It stops docker from running in any form.  I believe this is due to issue 504:
[https://github.com/NVIDIA/nvidia-docker/issues/504]

**Comment by LeitchP** [comment]
If I edit /ect/systemd/system/docker.service.d/override.config and remove the "--add runtime=nvidia=..." docker starts, and I can manually run the nvidia docker, and again see GPU details.

So I ran the entire original ExecStart and I got the message "unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives are specified as a flag and in the configuration file: runtimes: (from flag: [nvidia], from file: map[nvidia:map[path:nvidia-container-runtime runtimeArgs:[]]])

**Comment by flx42** [comment]
@LeitchP this `override` file was not added by nvidia-docker. How did you configure your machine?

**Comment by LeitchP** [comment]
Perhaps the file wasn't added by the install, but the install process made the bug.  To answer your question, this is a clean install on an Alienware laptop with 2x Geforce GTX 680 cards. These are the steps:
1: clean install of Ubuntu Desktop 18.04 
2: followed the steps to set up NVidia drivers
3: followed the steps to install docker-ce
  Confirmed multiple times that hello-world executes, even with log off/on and restarts.
4: followed the steps to install nvidia-docker2
  Confirmed multiple times that hello-world executes until the session is logged off, restarted, or the docker server is stopped and restarted.

So I'm not saying "override" was "added" by docker, I'm saying that the override file contained a specific reference to add the runtime=nvidia.  I'm also saying that I've traced the docker failing to that addition.  I'm also saying that if I stop at step 3 that "--add runtime" isn't present, but after step 4 it is.  

I'm being that specific because I haven't traced what is actually doing the modification.  For instance, this may be due to Cuda or some other auto-installs as a component/requirement of nvidia-docker2.

The next thing I'm going to try is another clean install of Ubuntu, and monitor that file step by step.

**Comment by LeitchP** [comment]
Is it the nvidia-docker file, line 16 that was modified by you on the 23rd of February?  That's what adds it to the override?  Or is it the June introduction of daemon.json that replaces (without backup) the existing daemon.json?  I'm going to do another clean install tomorrow, so let me know if there are steps I can snapshot for you that might help with this.

**Comment by flx42** [comment]
Are you referring to this? https://github.com/NVIDIA/nvidia-docker/commit/2e9f20b054d47089d97ff9a65d7af13cbfcd8fa5#diff-03550f513b5eb839088628d4a360b865
This only adds argument to the docker CLI.

`daemon.json` is the only file that we ship in our packages.

**Comment by LeitchP** [comment]
@flx42 Yes, that's the one I'm referring to.  This is the text contained in the override.conf:

`[Service]
ExecStart=
ExecStart=/usr/bin/dockerd --host=fd:// --add-runtime=nvidia=/usr/bin/nvidia-container-runtime`

**Comment by flx42** [comment]
What is the output of `dpkg -S /etc/systemd/system/docker.service.d/override.conf`?

**Comment by LeitchP** [comment]
@flx42 
it says "dpkg-query: no path found matching pattern *override.conf*"

I'm sorry if I am not understanding what you want to see. 
I couldn't find "-S" in the help to see what it would do for dpkg, but there was a lower case "-s" for status.   But that returned and error saying "Status needs a valid package name" and the file isn't a package.

**Comment by flx42** [comment]
`dpkg -S` tells you which package a file on your system comes from.
The output is telling me it was not installed by a package. So it was probably added manually or generated somehow.

**Comment by LeitchP** [comment]
@flx42 I don't follow your logic.

I tell you it is a clean install, and you tell me a file has probably manually generated?

I tell you that the file exists before installing NVIDIA-docker but is modified by the NVIDIA-docker install and you are focused on how the file is generated?   

However this confusion happened - and in the interest of getting to the root cause of the problem - I will detail every step, with screen shots:

1. An entirely fresh install of Ubuntu (you can see versions and even my hardware details).  I checked for updates and there were none.
![screenshot from 2018-07-27 10-30-18](https://user-images.githubusercontent.com/5144463/43295886-580f2e04-918b-11e8-9b60-0626fc4e8c34.png)
2. Install Chrome from their website download
3. Confirm the override.conf file does not exist.
![screenshot from 2018-07-27 10-55-23](https://user-images.githubusercontent.com/5144463/43295938-96555b2a-918b-11e8-9b35-98670b055ee9.png)
4. Went to [docker](https://www.docker.com/community-edition) and installed [Docker-CE](https://www.docker.com/community-edition) for Ubuntu using the "Install using the repository" steps.
![screenshot from 2018-07-27 10-57-44](https://user-images.githubusercontent.com/5144463/43296057-53dbacbc-918c-11e8-9ed8-973ff72ed740.png)
![screenshot from 2018-07-27 11-15-23](https://user-images.githubusercontent.com/5144463/43296388-699011f4-918e-11e8-96ee-7b3c21dc39d2.png)
5. Checked the override file still isn't there.  Ran the [Post-installation steps for Linux](https://docs.docker.com/install/linux/linux-postinstall/).  This attempts to create a docker group (which already exists for some reason), and adds the current user to that group. 
![screenshot from 2018-07-27 11-20-09](https://user-images.githubusercontent.com/5144463/43296503-1042136c-918f-11e8-8141-853b2bfb9c36.png)
At this point it needs to restart, so I will continue this on with another reply.

**Comment by flx42** [comment]
> However this confusion happened - and in the interest of getting to the root cause of the problem - I will detail every step, with screen shots:

Yes please, that's all I'm asking.

**Comment by LeitchP** [comment]
6. After restart check the file still isn't there and check docker now works without sudo (the reason for the reboot).
![screenshot from 2018-07-27 12-53-21](https://user-images.githubusercontent.com/5144463/43299977-14b29122-91a0-11e8-9ec1-0b137bcce724.png)

That was the completion of the "Manage Docker as a non-root user" of the Docker post install.
7. I performed the next step to "Configure Docker to start on boot". That allows the launching of Docker at startup.  I didn't do any further steps than that for docker, and before I did a restart the file still wasn't there.
![screenshot from 2018-07-27 13-56-28](https://user-images.githubusercontent.com/5144463/43300862-e141ca10-91a4-11e8-9f09-c34a07786137.png)

**Comment by LeitchP** [comment]
The NVidia driver instructions from [here](https://gist.github.com/wangruohui/df039f0dc434d6486f5d4d098aa52d07) were followed:
I got the most recent version of NVIDIA for Linux:
[http://uk.download.nvidia.com/XFree86/Linux-x86_64/390.77/NVIDIA-Linux-x86_64-390.77.run](http://uk.download.nvidia.com/XFree86/Linux-x86_64/390.77/NVIDIA-Linux-x86_64-390.77.run)

Ran ths:
`sudo apt-get install build-essential gcc-multilib dkms`

I created the "Blacklist for Nouveau Driver" and ran `sudo update-initramfs -u`
![screenshot from 2018-07-27 14-17-38](https://user-images.githubusercontent.com/5144463/43301331-d99ccc80-91a7-11e8-987e-51accd325c0c.png)

At that point the instructions indicate I need to restart.

**Comment by LeitchP** [comment]
After restart I continued with the steps:
![screenshot from 2018-07-27 14-39-04](https://user-images.githubusercontent.com/5144463/43302023-9a420b50-91ab-11e8-8517-1e7b5dcc972a.png)
![screenshot from 2018-07-27 14-39-43](https://user-images.githubusercontent.com/5144463/43302031-a5e7e952-91ab-11e8-8e6f-dec499a661dd.png)
![screenshot from 2018-07-27 14-40-52](https://user-images.githubusercontent.com/5144463/43302038-ab8fad22-91ab-11e8-9f7b-edb700d82700.png)

The override file still isn't there yet.

**Comment by LeitchP** [comment]
Downloaded Coda based on these settings (note Ubuntu 17 was the closest to 18 I could see)
![screenshot from 2018-07-27 14-49-11](https://user-images.githubusercontent.com/5144463/43302213-83ae16da-91ac-11e8-9b5a-fe1a7c5f12c0.png)

**Comment by LeitchP** [comment]
I followed the install instructions on this GIT Repo ([NVIDIA-nvidia-docker](https://github.com/NVIDIA/nvidia-docker))

![screenshot from 2018-07-27 15-15-14](https://user-images.githubusercontent.com/5144463/43302850-557f66c0-91b0-11e8-8ddb-aa231cb29676.png)

![screenshot from 2018-07-27 15-16-32](https://user-images.githubusercontent.com/5144463/43302854-5a274dd2-91b0-11e8-94da-11c44f2e851e.png)

**Comment by LeitchP** [comment]
I don't know what's different but not only is override.conf not there, 

I don't know if I had tried this and didn't remove it fully: [https://docs.docker.com/config/daemon/systemd/#httphttps-proxy](https://docs.docker.com/config/daemon/systemd/#httphttps-proxy)

But whatever the case, every time I removed NVIDA-nvidia-docker2 it would take the ammend to the override.conf out, and everything worked but every time I installed NVIDIA-nvidia-docker2 back in.

In fact, that would back up your assertion that the file was created manually, as per that link.

All I can say is that on a fresh Ubuntu install, with a fresh setup it appears to be working now, even with restarts.

**Comment by flx42** [comment]
Did you follow these instructions at one point?
https://github.com/nvidia/nvidia-container-runtime

That's one step too low in the stack for end users.

**Comment by LeitchP** [comment]
I think so. That looks familiar - I have my bash history before I cleared the system so I'll confirm.

**Comment by LeitchP** [comment]
Also, I apologise - you said I had created that manually and I stated I did not. Given those instructions, I did.

**Comment by flx42** [comment]
It looks like many users end up in this situation, I need to rephrase the README to redirect them to nvidia-docker instead.
