### ISSUE TITLE
share a GPU between multiple containers

### ISSUE THREAD

**Issue by acejim** [NVIDIA/nvidia-docker#808]
Hi there,

is it possible to share a GPU between multiple containers? I checked FAQs and the answer is yes, but the issue from kubernetes has investigated that nvidia-docker2 fails to achieve this. See the issue here #https://github.com/kubernetes/kubernetes/issues/52757#issuecomment-402636344.

I got confused by this.

**Comment by thomasjungblut** [comment]
With plain nvidia-docker2 it is possible to share a single GPU. The device plugin protocol of Kubernetes has a limitation to expose that case (which is correct IMHO).

**Comment by acejim** [comment]
@thomasjungblut , Thanks! Does Nvidia-supported Kubernetes solve this issue?

Another question is that is this sharing time-slice or any other style? For example, TF from Container-1 runs a very long time on GPU, will Container-1's TF prevent TF from Container-2 to occupy the GPU? Thank you.

**Comment by acejim** [comment]
@thomasjungblut Got it.

Based on intuition I don't think fair time-slicing is a good way to share GPU. As TF is very memory-consuming, frequent context switches between Container-1 and Container-2 could cause huge performance degradation. Let's leave it to Nvidia to answer it. Thanks!

**Comment by flx42** [comment]
> Thanks! Does Nvidia-supported Kubernetes solve this issue?

No, not right now.

> Sharing seems fair based by process so Container1 and Container2 get an equal share of duty cycles while running together at the same time, maybe Nvidia can supply more technical details.

It's difficult to say, it depends on your GPU compute architecture. Since Pascal you have instruction-level preemption, as described in the Pascal whitepaper page 30:
https://images.nvidia.com/content/pdf/tesla/whitepaper/pascal-architecture-whitepaper.pdf
But you can't set priorities or GPU shares. What you see might depend on the driver version and how your kernels are launched by your multiple applications.

>  frequent context switches between Container-1 and Container-2 could cause huge performance degradation. Let's leave it to Nvidia to answer it. Thanks!

Since Volta, there is a new tool for inference: Volta MPS (very different from pre-Volta MPS). You can look at the section "VOLTA MULTI-PROCESS SERVICE" in the Volta whitepaper:
http://images.nvidia.com/content/volta-architecture/pdf/volta-architecture-whitepaper.pdf
As figure 26 shows, the recommendation is still to use dynamic batching in your code. It requires more software logic but it usually yields better performance and doesn't require deploying MPS on the side.
Of course, if you have many models on the same GPU, you can't use dynamic batching.

Pre-Pascal you have neither of the above, so all bets are off regarding preemption, and you shouldn't use MPS for this use case.

**Comment by warmchang** [comment]
The trick: https://github.com/kubernetes/kubernetes/issues/52757#issuecomment-402772200

**Comment by RenaudWasTaken** [comment]
Hello!

See MPS for docker swarm: https://github.com/NVIDIA/nvidia-docker/wiki/MPS-(EXPERIMENTAL)

**Comment by whillas** [comment]
We're using Nvidia's [Triton Inference Server](https://github.com/triton-inference-server/server) to run many models on a single GPU on premise. Works fairly well but does have its foibles.

**Comment by Kshitij09-ag** [comment]
What's the status of support for GPU sharing today? I found the issue is still open on kubernetes repo but what's the status for swarm? Any updates on this? @whillas can you brief more about your experience with  [Triton Inference Server](https://github.com/triton-inference-server/server)?

Thanks!
