### ISSUE TITLE
Plugin.Activate, 400 Bad Request: malformed Host header

### ISSUE THREAD

**Issue by elezar** [NVIDIA/nvidia-docker#83]
When using the deb package to install `nvidia-docker` on a system running docker 1.9.1, the following message is presented when trying to start a container using `nvidia-docker`:
```
>nvidia-docker run nvida/cuda nvidia-smi
Error response from daemon: Error looking up volume plugin nvidia-docker: Plugin Error: Plugin.Activate, 400 Bad Request: malformed Host header
```
Upgrading to docker=1.10.3 solved this problem.

On production machines, we still have to use 1.9.1, so if 1.9 is really the minimum requirement it would be great if this would work. Alternatively, the wiki page should be updated.

**Comment by 3XX0** [comment]
This incompatibility is due to a breaking change in the Go http package.
Docker 1.9 is probably compiled against Go 1.5 while `nvidia-docker` is compiled against 1.6
Try changing `FROM golang` to `FROM golang:1.5` [here](https://github.com/NVIDIA/nvidia-docker/blob/master/tools/Dockerfile.build#L1) and rebuild `nvidia-docker` from [sources](https://github.com/NVIDIA/nvidia-docker/wiki/Installation#building-from-sources)

**Comment by elezar** [comment]
Thanks for the tip!

**Comment by elezar** [comment]
Sorry, did not want to close (it can be if you like).

**Comment by 3XX0** [comment]
Does it work? If it fixes the problem we might want to stick to Go 1.5

**Comment by elezar** [comment]
Hi, I have already solved the problem by upgrading docker. I will see if I can replicate and test the fix as soon as I have access to the system again.

**Comment by elezar** [comment]
I have just had a chance to test on another system that showed the same behaviour, and I can confirm that switching to the `golang:1.5` base image no longer shows the message that I originally reported (and allows for docker 1.9.1 to be used).
