### ISSUE TITLE
Amazon Linux is lacking the correct docker package

### ISSUE THREAD

**Issue by aplumb-neurala** [NVIDIA/nvidia-docker#870]
I'm trying to install nvidia-docker2 on Amazon Linux and am running into a dependency error:
```
Error: Package: nvidia-docker2-2.0.3-1.docker18.06.1.ce.amzn1.noarch (nvidia-docker)
           Requires: docker = 18.06.1ce
           Installed: docker-17.12.1ce-1.135.amzn1.x86_64 (@amzn-updates)
               docker = 17.12.1ce-1.135.amzn1
           Available: docker-17.03.2ce-1.59.amzn1.x86_64 (amzn-main)
               docker = 17.03.2ce-1.59.amzn1
           Available: docker-17.06.2ce-1.93.amzn1.x86_64 (amzn-updates)
               docker = 17.06.2ce-1.93.amzn1
           Available: docker-17.06.2ce-1.94.amzn1.x86_64 (amzn-updates)
               docker = 17.06.2ce-1.94.amzn1
           Available: docker-17.09.1ce-1.111.amzn1.x86_64 (amzn-updates)
               docker = 17.09.1ce-1.111.amzn1
           Available: docker-17.12.0ce-1.129.amzn1.x86_64 (amzn-updates)
               docker = 17.12.0ce-1.129.amzn1
 You could try using --skip-broken to work around the problem
```

For now I can get it working by installing `nvidia-docker2-2.0.3-1.docker17.12.1.ce.amzn1` but I'm assuming we're missing an up to date package for Amazon Linux.

Is there a way we can make the release process more reliable?  This seems like an easy problem to solve.

**Comment by RenaudWasTaken** [comment]
Hello!

Unfortunately, nvidia-docker releases are tied to docker releases. Which means that in your case because you have docker-17.12.1 you need to install nvidia-docker2 with the docker version 17.12.1

It seems like you've found the correct command, note that this is documented here: https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#how-do-i-install-20-if-im-not-using-the-latest-docker-version

Thanks!
