### ISSUE TITLE
Wiki manual installation instruction missing a step

### ISSUE THREAD

**Issue by nouiz** [NVIDIA/nvidia-docker#88]
This section of the wiki:

https://github.com/NVIDIA/nvidia-docker/wiki/Installation#building-from-sources

Is missing this step after the manual installation:

    sudo ./nvidia-docker volume setup

Yes, it is in this doc section:

https://github.com/NVIDIA/nvidia-docker/wiki/Using-nvidia-docker#standalone-version

As as this is a requested step to run the samples, I think it should be in the installation instruction, as many people like myself would jump from the installation section to the sample section to test the installation. Then later, take the time to read how to use it in more detail.

**Comment by flx42** [comment]
Actually, `nvidia-docker volume setup` is only required if you don't want to rely on the volume plugin, see:
https://github.com/NVIDIA/nvidia-docker/wiki/Using-nvidia-docker#with-the-nvidia-docker-plugin
An alternative is therefore to either install the deb (after `make deb`) or to launch the plugin with `sudo -b nohup nvidia-docker-plugin` (after `make install`).
We recommend the plugin approach because volume plugins are now part of the Docker ecosystem.

**Comment by nouiz** [comment]
Ok. What about adding a link or a note in the section

https://github.com/NVIDIA/nvidia-docker/wiki/Installation#building-from-sources

To tell about this step to get something working?

**Comment by flx42** [comment]
I added a note to the documentation, thank you!
