### ISSUE TITLE
Listing of nvidia-docker plugin version

### ISSUE THREAD

**Issue by ruffsl** [NVIDIA/nvidia-docker#90]
Would it be possible for say `nvidia-docker -v` to list version of itself (the plugin) in perhaps addition to the  the docker engine version it's connected to? Currently it just ouputs the former. On any given system I log into, I'd like to quickly find out what version of the plugin I'm working with.

**Comment by 3XX0** [comment]
We print the version in `nvidia-docker` (see [here](https://github.com/NVIDIA/nvidia-docker/blob/master/tools/src/nvidia-docker/main.go#L57)). It is done through the `version` command because parsing `docker` arguments is somewhat a pain.

However, this feature is lacking in `nvidia-docker-plugin`. Most of the time they are the same but maybe it's worth adding if you are dealing with the plugin remotely.
