### ISSUE TITLE
Where are apt repos

### ISSUE THREAD

**Issue by oricou** [NVIDIA/nvidia-docker#976]
I tried to get nvidia-docker.list to be able to download nvidia-docker. I use Mint which is an Ubuntu which is supported, so it should be easy.

Well it is not. I lost 20 minutes trying to guess (since I have no Ubuntu) what is the magic word for $distribution is in

```
https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list
```
It is very nice to make magic so it works without understanding anything, very Microsoft spirit but what about the KISS spirit? Could your just list with links the repositories or the nvidia-docker.list?

**Comment by oricou** [comment]
got it!

```
# cat nvidia-docker.list 
deb https://nvidia.github.io/libnvidia-container/ubuntu18.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-container-runtime/ubuntu18.04/$(ARCH) /
deb https://nvidia.github.io/nvidia-docker/ubuntu18.04/$(ARCH) /
```

No upper case to Ubuntu and full version, not just 18.

**Comment by RenaudWasTaken** [comment]
Hello @oricou!

The list of supported distribution is available on the gh-pages branch : https://github.com/NVIDIA/nvidia-docker/tree/gh-pages

We intend to deprecate these packages (in around a year) since the new version of docker has a native plugin integration (docker run - - GPU).

We will document this as soon as 19.03 comes out.

**Comment by oricou** [comment]
Thanks !
Until it becomes deprecated, maybe you could put this link in this page: 
https://nvidia.github.io/nvidia-docker/

**Comment by RenaudWasTaken** [comment]
Pull request accepted.
