### ISSUE TITLE
Error: unsupported CUDA version: driver 0.0 < image 7.5

### ISSUE THREAD

**Issue by tboquet** [NVIDIA/nvidia-docker#99]
Hello, I have a strange behavior of the plugin.

I can use `nvidia-smi` and I have an output:
```
Wed May 25 14:21:37 2016
+------------------------------------------------------+
| NVIDIA-SMI 361.42     Driver Version: 361.42         |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 980 Ti  Off  | 0000:06:00.0      On |                  N/A |
|  0%   57C    P8    26W / 390W |     89MiB /  6143MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      2116    G   /usr/bin/X                                      38MiB |
|    0      2518    G   gnome-shell                                     26MiB |
+-----------------------------------------------------------------------------+
```

But I can't start the plugin anymore:
```
nvidia-docker-plugin | 2016/05/25 14:24:10 Loading NVIDIA unified memory
nvidia-docker-plugin | 2016/05/25 14:24:10 Loading NVIDIA management library
nvidia-docker-plugin | 2016/05/25 14:24:10 Discovering GPU devices
nvidia-docker-plugin | 2016/05/25 14:24:10 Error: cuda: CUDA driver version is insufficient for CUDA runtime version
```

And if I try to run the `nvidia-smi` container:
```
nvidia-docker | 2016/05/25 14:32:15 Error: unsupported CUDA version: driver 0.0 < image 7.5
```

I'm not sure if it's a problem with the drivers or the plugin.

**Comment by ruffsl** [comment]
Did you update your host's nvidia driver without updating the nvidia docker plugin's driver volume?
`sudo nvidia-docker volume setup`

**Comment by flx42** [comment]
Weird, looks like your install might be messed up.
Can you try to run the deviceQuery sample on your host? It's in `/usr/local/cuda/samples/1_Utilities/deviceQuery`

@ruffsl: please don't use `volume setup` if you run the plugin :)

**Comment by ruffsl** [comment]
@flx42 , odd. After just installing the deb on a fresh image of Ubuntu Xenial, I couldn't get `nvidia-docker run --rm nvidia/cuda nvidia-smi` to work without first setting up the volume. However I just removed it manually and the plugin still works (although it looks like it just recreated the same volume again). So I'm not sure why it wouldn't also be susceptible the driver changing underneath it. If the plugin creates it, does it then monitor the installed driver version and remove the existing volume when they conflict?

**Comment by flx42** [comment]
@ruffsl The plugin will create the volume on-demand (when nvidia-docker is used to launch a container). The volume name is versioned accordingly to the driver version, for instance: ```nvidia_driver_367.20```
If you upgrade your driver, the old volume will be kept but a new one might be created.
I don't know why you couldn't make it work on a fresh xenial install, maybe you should file another issue.

**Comment by tboquet** [comment]
So it seems it was a bug with the drivers because of an `autoremove` and some messy manipulations.
CUDA was uninstalled from the host so I wasn't able to run the samples.
I've cleaned everything, reinstalled the drivers using the latest install script for my GPU and reinstalled the plugin and everything is back to normal now.
Tx for the help!

**Comment by flx42** [comment]
Cool! As a general advise, never switch directly from a driver installed with a `.run` file to a driver installed from a deb package (nor the other way around). Do a full uninstall first.

`.run` -> deb: first use `nvidia-uninstall` to fully remove the driver, reboot then use the deb.

deb -> `.run`: list all the nvidia packages that are tied to your driver version (e.g. `dpkg -l | grep '361\.59') and purge them using `apt-get remove --purge ...`, reboot then use the `.run`.

**Comment by vskubriev** [comment]
@tboquet Thank you for a tip.

I face with same problem on 367 driver installed from [this famous ppa](https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa) on ubuntu 14.04:

```
root@venus:/home/sysadmin# LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/nvidia-367 nvidia-docker run --rm nvidia/cuda nvidia-smi
nvidia-docker | 2016/08/16 11:32:40 Error: unsupported CUDA version: driver 0.0 < image 8.0
```

I have came to the following:

1. Available from official ubuntu repo drivers not supporting our NVIDIA 1070 GPU's. Therefore we can install drivers from this [ppa](https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa) or install driver from runfile `NVIDIA-Linux-x86_64-367.35.run`. With driver from ppa we cannot use cuda because of same (identical) error. With driver from run file we cannot configure XServer to start on Intel iGPU. 

With ppa(beta ubuntu official) driver I was tried to use prime-switch, which is doing some magic with libs. XServer starts on iGPU, but unfortunately nvidia-docker does not work with same error.

Also if I switch `prime-select` with `intel` option, I need to add env variable `LD_LIBRARY_PATH` ahead nvidia-docker run.

2. Driver from ppa does not loading nvidia-367-uvm module automatically. But nvidia-docker does it automatically. But it is a trifle compared with starting XServer on iGPU.

The final goal is:

a. Starting XServer without hardcoding xorg.conf or doing something else that can break default ubuntu gpumanager. Use build-in iGPU adapter on Intel CPU for developer desktop.

b. Uses nvidia-docker.

**Comment by vskubriev** [comment]
Installing `NVIDIA-Linux-x86_64-367.35.run` with `--no-opengl-files` has solved the problem.
